// Code generated by 'yaegi extract cogentcore.org/lab/physics/phyxyz'. DO NOT EDIT.

package labsymbols

import (
	"cogentcore.org/lab/physics/phyxyz"
	"reflect"
)

func init() {
	Symbols["cogentcore.org/lab/physics/phyxyz/phyxyz"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DepthImage":       reflect.ValueOf(phyxyz.DepthImage),
		"DepthNorm":        reflect.ValueOf(phyxyz.DepthNorm),
		"MakeStateToolbar": reflect.ValueOf(phyxyz.MakeStateToolbar),
		"NewEditor":        reflect.ValueOf(phyxyz.NewEditor),
		"NewWorld":         reflect.ValueOf(phyxyz.NewWorld),
		"NoDisplayScene":   reflect.ValueOf(phyxyz.NoDisplayScene),

		// type definitions
		"Camera": reflect.ValueOf((*phyxyz.Camera)(nil)),
		"Editor": reflect.ValueOf((*phyxyz.Editor)(nil)),
		"View":   reflect.ValueOf((*phyxyz.View)(nil)),
		"World":  reflect.ValueOf((*phyxyz.World)(nil)),
	}
}
