// Code generated by 'yaegi extract cogentcore.org/lab/plotcore'. DO NOT EDIT.

package labsymbols

import (
	"cogentcore.org/lab/plotcore"
	"reflect"
)

func init() {
	Symbols["cogentcore.org/lab/plotcore/plotcore"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BasicStylers":      reflect.ValueOf(plotcore.BasicStylers),
		"NewEditor":         reflect.ValueOf(plotcore.NewEditor),
		"NewPlot":           reflect.ValueOf(plotcore.NewPlot),
		"NewPlotterChooser": reflect.ValueOf(plotcore.NewPlotterChooser),
		"NewSubPlot":        reflect.ValueOf(plotcore.NewSubPlot),
		"SetBasicStylers":   reflect.ValueOf(plotcore.SetBasicStylers),

		// type definitions
		"Editor":         reflect.ValueOf((*plotcore.Editor)(nil)),
		"Plot":           reflect.ValueOf((*plotcore.Plot)(nil)),
		"PlotterChooser": reflect.ValueOf((*plotcore.PlotterChooser)(nil)),
	}
}
