// Code generated by 'yaegi extract cogentcore.org/lab/physics/builder'. DO NOT EDIT.

package labsymbols

import (
	"cogentcore.org/lab/physics/builder"
	"reflect"
)

func init() {
	Symbols["cogentcore.org/lab/physics/builder/builder"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"MakePoseToolbar": reflect.ValueOf(builder.MakePoseToolbar),
		"NewBuilder":      reflect.ValueOf(builder.NewBuilder),

		// type definitions
		"Body":    reflect.ValueOf((*builder.Body)(nil)),
		"Builder": reflect.ValueOf((*builder.Builder)(nil)),
		"DoF":     reflect.ValueOf((*builder.DoF)(nil)),
		"Joint":   reflect.ValueOf((*builder.Joint)(nil)),
		"Object":  reflect.ValueOf((*builder.Object)(nil)),
		"Pose":    reflect.ValueOf((*builder.Pose)(nil)),
		"World":   reflect.ValueOf((*builder.World)(nil)),
	}
}
