// Code generated by "gosl"; DO NOT EDIT
// kernel: CollisionBroad

// // Params are global parameters. 
@group(0) @binding(0)
var<storage, read> TensorStrides: array<u32>;
@group(0) @binding(1)
var<storage, read_write> Params: array<PhysParams>;
// // Bodies are the rigid body elements (dynamic and static), // specifying the constant, non-dynamic properties, // which is initial state for dynamics. // [body][BodyVarsN] 
@group(1) @binding(0)
var<storage, read_write> Bodies: array<f32>;
@group(1) @binding(4)
var<storage, read_write> BodyCollidePairs: array<i32>;
// // Dynamics are the dynamic rigid body elements: these actually move. // Two alternating states are used: Params.Cur and Params.Next. // [dyn body][cur/next][DynamicVarsN] 
@group(2) @binding(0)
var<storage, read_write> Dynamics: array<f32>;
@group(2) @binding(1)
var<storage, read_write> BroadContactsN: array<atomic<i32>>;
@group(2) @binding(2)
var<storage, read_write> BroadContacts: array<f32>;
// // JointControls are dynamic joint control inputs, per joint DoF // (in correspondence with [JointDoFs]). This can be uploaded to the // GPU at every step. // [dof][JointControlVarsN] 

alias GPUVars = i32;

@compute @workgroup_size(64, 1, 1)
fn main(@builtin(workgroup_id) wgid: vec3<u32>, @builtin(num_workgroups) nwg: vec3<u32>, @builtin(local_invocation_index) loci: u32) {
	let idx = loci + (wgid.x + wgid.y * nwg.x + wgid.z * nwg.x * nwg.y) * 64;
	CollisionBroad(idx);
}

fn Index2D(s0: u32, s1: u32, i0: u32, i1: u32) -> u32 {
	return s0 * i0 + s1 * i1;
}

fn Index3D(s0: u32, s1: u32, s2: u32, i0: u32, i1: u32, i2: u32) -> u32 {
	return s0 * i0 + s1 * i1 + s2 * i2;
}

fn Index1D(s0: u32, i0: u32) -> u32 {
	return s0 * i0;
}


//////// import: "vars.go"

//////// import: "body.go"
alias BodyVars = i32; //enums:enum
const  BodyShape: BodyVars = 0;
const  BodyDynamic: BodyVars = 1;
const  BodyWorld: BodyVars = 2;
const  BodyGroup: BodyVars = 3;
const  BodyObject: BodyVars = 4;
const  BodyHSizeX: BodyVars = 5;
const  BodyHSizeY: BodyVars = 6;
const  BodyHSizeZ: BodyVars = 7;
const  BodyThick: BodyVars = 8;
const  BodyMass: BodyVars = 9;
const  BodyInvMass: BodyVars = 10;
const  BodyBounce: BodyVars = 11;
const  BodyFriction: BodyVars = 12;
const  BodyFrictionTortion: BodyVars = 13;
const  BodyFrictionRolling: BodyVars = 14;
const  BodyPosX: BodyVars = 15;
const  BodyPosY: BodyVars = 16;
const  BodyPosZ: BodyVars = 17;
const  BodyQuatX: BodyVars = 18;
const  BodyQuatY: BodyVars = 19;
const  BodyQuatZ: BodyVars = 20;
const  BodyQuatW: BodyVars = 21;
const  BodyComX: BodyVars = 22;
const  BodyComY: BodyVars = 23;
const  BodyComZ: BodyVars = 24;
const  BodyInertiaXX: BodyVars = 25;
const  BodyInertiaYX: BodyVars = 26;
const  BodyInertiaZX: BodyVars = 27;
const  BodyInertiaXY: BodyVars = 28;
const  BodyInertiaYY: BodyVars = 29;
const  BodyInertiaZY: BodyVars = 30;
const  BodyInertiaXZ: BodyVars = 31;
const  BodyInertiaYZ: BodyVars = 32;
const  BodyInertiaZZ: BodyVars = 33;
const  BodyInvInertiaXX: BodyVars = 34;
const  BodyInvInertiaYX: BodyVars = 35;
const  BodyInvInertiaZX: BodyVars = 36;
const  BodyInvInertiaXY: BodyVars = 37;
const  BodyInvInertiaYY: BodyVars = 38;
const  BodyInvInertiaZY: BodyVars = 39;
const  BodyInvInertiaXZ: BodyVars = 40;
const  BodyInvInertiaYZ: BodyVars = 41;
const  BodyInvInertiaZZ: BodyVars = 42;
const  BodyRadius: BodyVars = 43;
fn GetBodyShape(idx: i32) -> Shapes {
	return Shapes(bitcast<u32>(Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(idx), u32(BodyShape))]));
}
fn GetBodyDynamic(idx: i32) -> i32 {
	return i32(bitcast<u32>(Bodies[Index2D(TensorStrides[0], TensorStrides[1],
	u32(idx), u32(BodyDynamic))]));
}
fn BodyHSize(idx: i32) -> vec3<f32> {
	return vec3<f32>(Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(idx), u32(BodyHSizeX))], Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(idx), u32(BodyHSizeY))], Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(idx), u32(BodyHSizeZ))]);
}
fn BodyPos(idx: i32) -> vec3<f32> {
	return vec3<f32>(Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(idx), u32(BodyPosX))], Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(idx), u32(BodyPosY))], Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(idx), u32(BodyPosZ))]);
}
fn BodyQuat(idx: i32) -> vec4<f32> {
	return vec4<f32>(Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(idx), u32(BodyQuatX))], Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(idx), u32(BodyQuatY))], Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(idx), u32(BodyQuatZ))], Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(idx), u32(BodyQuatW))]);
}
fn BodyDynamicPos(idx: i32,cni: i32) -> vec3<f32> {
	var didx = GetBodyDynamic(idx);
	if (didx < 0) {
		return BodyPos(idx);
	}return DynamicPos(didx, cni);
}
fn BodyDynamicQuat(idx: i32,cni: i32) -> vec4<f32> {
	var didx = GetBodyDynamic(idx);
	if (didx < 0) {
		return BodyQuat(idx);
	}return DynamicQuat(didx, cni);
}

//////// import: "contact.go"
alias ContactVars = i32; //enums:enum
const  ContactA: ContactVars = 0;
const  ContactB: ContactVars = 1;
const  ContactPointIdx: ContactVars = 2;
const  ContactAPointX: ContactVars = 3;
const  ContactAPointY: ContactVars = 4;
const  ContactAPointZ: ContactVars = 5;
const  ContactBPointX: ContactVars = 6;
const  ContactBPointY: ContactVars = 7;
const  ContactBPointZ: ContactVars = 8;
const  ContactAOffX: ContactVars = 9;
const  ContactAOffY: ContactVars = 10;
const  ContactAOffZ: ContactVars = 11;
const  ContactBOffX: ContactVars = 12;
const  ContactBOffY: ContactVars = 13;
const  ContactBOffZ: ContactVars = 14;
const  ContactAThick: ContactVars = 15;
const  ContactBThick: ContactVars = 16;
const  ContactNormX: ContactVars = 17;
const  ContactNormY: ContactVars = 18;
const  ContactNormZ: ContactVars = 19;
const  ContactWeight: ContactVars = 20;
const  ContactADeltaX: ContactVars = 21;
const  ContactADeltaY: ContactVars = 22;
const  ContactADeltaZ: ContactVars = 23;
const  ContactAAngDeltaX: ContactVars = 24;
const  ContactAAngDeltaY: ContactVars = 25;
const  ContactAAngDeltaZ: ContactVars = 26;
const  ContactBDeltaX: ContactVars = 27;
const  ContactBDeltaY: ContactVars = 28;
const  ContactBDeltaZ: ContactVars = 29;
const  ContactBAngDeltaX: ContactVars = 30;
const  ContactBAngDeltaY: ContactVars = 31;
const  ContactBAngDeltaZ: ContactVars = 32;
const BroadContactVarsN = ContactAPointX;
fn SetBroadContactA(idx: i32,bodIdx: i32) {
	BroadContacts[Index2D(TensorStrides[70], TensorStrides[71], u32(idx), u32(ContactA))] = bitcast<f32>(u32(bodIdx));
}
fn SetBroadContactB(idx: i32,bodIdx: i32) {
	BroadContacts[Index2D(TensorStrides[70], TensorStrides[71], u32(idx), u32(ContactB))] = bitcast<f32>(u32(bodIdx));
}
fn SetBroadContactPointIdx(idx: i32,ptIdx: i32) {
	BroadContacts[Index2D(TensorStrides[70], TensorStrides[71], u32(idx), u32(ContactPointIdx))] = bitcast<f32>(u32(ptIdx));
}
fn CollisionBroad(i: u32) { //gosl:kernel
	var params = Params[0];
	var ci = i32(i);
	if (ci >= params.BodyCollidePairsN) {
		return;
	}
	var biA = BodyCollidePairs[Index2D(TensorStrides[40], TensorStrides[41], u32(ci), u32(0))];
	var biB = BodyCollidePairs[Index2D(TensorStrides[40], TensorStrides[41], u32(ci), u32(1))];
	var xwAR = BodyDynamicPos(biA, params.Cur);
	var xwAQ = BodyDynamicQuat(biA, params.Cur);
	var xwBR = BodyDynamicPos(biB, params.Cur);
	var sA = GetBodyShape(biA);
	var sB = GetBodyShape(biB);
	var rb = Bodies[Index2D(TensorStrides[0], TensorStrides[1],
	u32(biB), u32(BodyRadius))];
	var margin = params.ContactMargin;
	var infPlane = false;
	if (sA == Plane) {
		var szA = BodyHSize(biA);
		if (szA.x == 0) {
			infPlane = true;
		}
		var queryB = MulSpatialPoint(xwAR, xwAQ, xwBR);
		var closest = ClosestPointPlane(szA.x, szA.z, queryB);
		var d = Length3(queryB-(closest));
		if (d > rb+margin) {
			return;
		}
	} else {
		var d = Length3(xwAR-(xwBR));
		var ra = Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(biA), u32(BodyRadius))];
		if (d > ra+rb+margin) {
			return;
		}
	}
	var ncB: i32;
	var ncA = ShapePairContacts(sA, sB, infPlane, &ncB);
	var enci = atomicAdd(&BroadContactsN[0], ncA+ncB);
	enci += ncA + ncB; // wgsl now matches Go
	var nci = enci - (ncA + ncB);    // starting index
	if (nci >= params.ContactsMax) { // shouldn't happen!
		return;
	}
	AddBroadContacts(biA, biB, nci, ncA, ncB);
	Params[0] = params;
}
fn AddBroadContacts(biA: i32,biB: i32,nci: i32,ncA: i32,ncB: i32) {
	for (var i=0; i<ncA; i++) {
		SetBroadContactA(nci+i, biA);
		SetBroadContactB(nci+i, biB);
		SetBroadContactPointIdx(nci+i, i);
	}
	for (var i=0; i<ncB; i++) {
		SetBroadContactA(nci+ncA+i, biB); // flipped
		SetBroadContactB(nci+ncA+i, biA);
		SetBroadContactPointIdx(nci+i, i);
	}
}

//////// import: "control.go"
alias JointControlVars = i32; //enums:enum
const  JointControlForce: JointControlVars = 0;
const  JointTargetStiff: JointControlVars = 1;
const  JointTargetPos: JointControlVars = 2;
const  JointTargetDamp: JointControlVars = 3;
const  JointTargetVel: JointControlVars = 4;

//////// import: "dynamics.go"
alias DynamicVars = i32; //enums:enum
const  DynBody: DynamicVars = 0;
const  DynPosX: DynamicVars = 1;
const  DynPosY: DynamicVars = 2;
const  DynPosZ: DynamicVars = 3;
const  DynQuatX: DynamicVars = 4;
const  DynQuatY: DynamicVars = 5;
const  DynQuatZ: DynamicVars = 6;
const  DynQuatW: DynamicVars = 7;
const  DynVelX: DynamicVars = 8;
const  DynVelY: DynamicVars = 9;
const  DynVelZ: DynamicVars = 10;
const  DynAngVelX: DynamicVars = 11;
const  DynAngVelY: DynamicVars = 12;
const  DynAngVelZ: DynamicVars = 13;
const  DynAccX: DynamicVars = 14;
const  DynAccY: DynamicVars = 15;
const  DynAccZ: DynamicVars = 16;
const  DynAngAccX: DynamicVars = 17;
const  DynAngAccY: DynamicVars = 18;
const  DynAngAccZ: DynamicVars = 19;
const  DynForceX: DynamicVars = 20;
const  DynForceY: DynamicVars = 21;
const  DynForceZ: DynamicVars = 22;
const  DynTorqueX: DynamicVars = 23;
const  DynTorqueY: DynamicVars = 24;
const  DynTorqueZ: DynamicVars = 25;
const  DynDeltaX: DynamicVars = 26;
const  DynDeltaY: DynamicVars = 27;
const  DynDeltaZ: DynamicVars = 28;
const  DynAngDeltaX: DynamicVars = 29;
const  DynAngDeltaY: DynamicVars = 30;
const  DynAngDeltaZ: DynamicVars = 31;
const  DynContactWeight: DynamicVars = 32;
fn DynamicPos(idx: i32,cni: i32) -> vec3<f32> {
	return vec3<f32>(Dynamics[Index3D(TensorStrides[50], TensorStrides[51], TensorStrides[52], u32(idx), u32(cni), u32(DynPosX))], Dynamics[Index3D(TensorStrides[50], TensorStrides[51], TensorStrides[52], u32(idx), u32(cni), u32(DynPosY))], Dynamics[Index3D(TensorStrides[50], TensorStrides[51], TensorStrides[52], u32(idx), u32(cni), u32(DynPosZ))]);
}
fn DynamicQuat(idx: i32,cni: i32) -> vec4<f32> {
	return vec4<f32>(Dynamics[Index3D(TensorStrides[50], TensorStrides[51], TensorStrides[52], u32(idx), u32(cni), u32(DynQuatX))], Dynamics[Index3D(TensorStrides[50], TensorStrides[51], TensorStrides[52], u32(idx), u32(cni), u32(DynQuatY))], Dynamics[Index3D(TensorStrides[50], TensorStrides[51], TensorStrides[52], u32(idx), u32(cni), u32(DynQuatZ))], Dynamics[Index3D(TensorStrides[50], TensorStrides[51], TensorStrides[52], u32(idx), u32(cni), u32(DynQuatW))]);
}

//////// import: "enumgen.go"
const BodyVarsN: BodyVars = 43;
const ContactVarsN: ContactVars = 33;
const JointControlVarsN: JointControlVars = 5;
const DynamicVarsN: DynamicVars = 33;
const GPUVarsN: GPUVars = 12;
const JointTypesN: JointTypes = 7;
const JointVarsN: JointVars = 50;
const JointDoFVarsN: JointDoFVars = 5;
const ShapesN: Shapes = 6;

//////// import: "joint.go"
const JointLimitUnlimited = 1e10;
alias JointTypes = i32; //enums:enum
const  Prismatic: JointTypes = 0;
const  Revolute: JointTypes = 1;
const  Ball: JointTypes = 2;
const  Fixed: JointTypes = 3;
const  Free: JointTypes = 4;
const  Distance: JointTypes = 5;
const  D6: JointTypes = 6;
alias JointVars = i32; //enums:enum
const  JointType: JointVars = 0;
const  JointEnabled: JointVars = 1;
const  JointParent: JointVars = 2;
const  JointChild: JointVars = 3;
const  JointPPosX: JointVars = 4;
const  JointPPosY: JointVars = 5;
const  JointPPosZ: JointVars = 6;
const  JointPQuatX: JointVars = 7;
const  JointPQuatY: JointVars = 8;
const  JointPQuatZ: JointVars = 9;
const  JointPQuatW: JointVars = 10;
const  JointCPosX: JointVars = 11;
const  JointCPosY: JointVars = 12;
const  JointCPosZ: JointVars = 13;
const  JointCQuatX: JointVars = 14;
const  JointCQuatY: JointVars = 15;
const  JointCQuatZ: JointVars = 16;
const  JointCQuatW: JointVars = 17;
const  JointLinearDoFN: JointVars = 18;
const  JointAngularDoFN: JointVars = 19;
const  JointDoF1: JointVars = 20;
const  JointDoF2: JointVars = 21;
const  JointDoF3: JointVars = 22;
const  JointDoF4: JointVars = 23;
const  JointDoF5: JointVars = 24;
const  JointDoF6: JointVars = 25;
const  JointPForceX: JointVars = 26;
const  JointPForceY: JointVars = 27;
const  JointPForceZ: JointVars = 28;
const  JointPTorqueX: JointVars = 29;
const  JointPTorqueY: JointVars = 30;
const  JointPTorqueZ: JointVars = 31;
const  JointCForceX: JointVars = 32;
const  JointCForceY: JointVars = 33;
const  JointCForceZ: JointVars = 34;
const  JointCTorqueX: JointVars = 35;
const  JointCTorqueY: JointVars = 36;
const  JointCTorqueZ: JointVars = 37;
const  JointPDeltaX: JointVars = 38;
const  JointPDeltaY: JointVars = 39;
const  JointPDeltaZ: JointVars = 40;
const  JointPAngDeltaX: JointVars = 41;
const  JointPAngDeltaY: JointVars = 42;
const  JointPAngDeltaZ: JointVars = 43;
const  JointCDeltaX: JointVars = 44;
const  JointCDeltaY: JointVars = 45;
const  JointCDeltaZ: JointVars = 46;
const  JointCAngDeltaX: JointVars = 47;
const  JointCAngDeltaY: JointVars = 48;
const  JointCAngDeltaZ: JointVars = 49;
alias JointDoFVars = i32; //enums:enum
const  JointAxisX: JointDoFVars = 0;
const  JointAxisY: JointDoFVars = 1;
const  JointAxisZ: JointDoFVars = 2;
const  JointLimitLower: JointDoFVars = 3;
const  JointLimitUpper: JointDoFVars = 4;

//////// import: "params.go"
struct PhysParams {
	Iterations: i32,
	Dt: f32,
	SubSteps: i32,
	ContactMargin: f32,
	ContactRelax: f32, // 0.8 def
	ContactWeighting: i32, // true
	Restitution: i32, // false
	JointLinearRelax: f32, // 0.7 def
	JointAngularRelax: f32, // 0.4 def
	JointLinearComply: f32, // 0 def
	JointAngularComply: f32, // 0 def
	AngularDamping: f32, // 0 def
	SoftRelax: f32,
	MaxGeomIter: i32,
	ContactsMax: i32,
	Cur: i32,
	Next: i32,
	BodiesN: i32,
	DynamicsN: i32,
	JointsN: i32,
	JointDoFsN: i32,
	BodyJointsMax: i32,
	BodyCollidePairsN: i32,
	pad: i32,
	Gravity: vec4<f32>,
}

//////// import: "shapecollide.go"
struct GeomData {
	BodyIdx: i32,
	Shape: Shapes,
	MinSize: f32,
	Thick: f32,
	Radius: f32,
	Size: vec3<f32>,
	WbR: vec3<f32>,
	WbQ: vec4<f32>,
	BwR: vec3<f32>,
	BwQ: vec4<f32>,
}

//////// import: "shapegeom.go"
fn ClosestPointPlane(width: f32,length: f32, pt: vec3<f32>) -> vec3<f32> {
	var cp = pt;
	cp.y = f32(0);
	if (width == 0.0) {
		return cp;
	}
	cp.x = clamp(pt.x, -width, width);
	cp.z = clamp(pt.z, -length, length);
return cp;
}

//////// import: "shapes.go"
alias Shapes = i32; //enums:enum
const  Plane: Shapes = 0;
const  Sphere: Shapes = 1;
const  Capsule: Shapes = 2;
const  Cylinder: Shapes = 3;
const  Box: Shapes = 4;
const  Cone: Shapes = 5;
fn ShapePairContacts(a: Shapes,b: Shapes, infPlane: bool, ba: ptr<function,i32>) -> i32 {
	*ba = i32(0);
	switch (a) {
	case Plane: {
		switch (b) {
		case Plane: {
			return i32(0);
		}
		case Sphere: {
			return i32(1);
		}
		case Capsule: {
			if (infPlane) {
				return i32(2);
			} else {
				return 2 + 4;
			}
		}
		case Cylinder: {
			return i32(4);
		}
		case Box: {
			if (infPlane) {
				return i32(8);
			} else {
				return 8 + 4;
			}
		}
		default: {
			return i32(0);
		}
		}
	}
	case Sphere: {
		return i32(1);
	}
	case Capsule: {
		switch (b) {
		case Capsule: {
			return i32(2);
		}
		case Box: {
			return i32(8);
		}
		default: {
			return i32(0);
		}
		}
	}
	case Cylinder: {
		return i32( // no box collisions!
		0);
	}
	case Box: {
		*ba = i32(12);
		return i32(12);
	}
	default: { // note: Cone has no collision points!
		return i32(0);
	}
	}
}

//////// import: "slmath-matrix3.go"

//////// import: "slmath-quaternion.go"
fn MulQuatVector(q: vec4<f32>, v: vec3<f32>) -> vec3<f32> {
	var xyz = vec3<f32>(q.x, q.y, q.z);
	var t = Cross3(xyz, v)*(2);
return v+(t*(q.w))+(Cross3(xyz, t));
}
fn MulSpatialPoint(xP: vec3<f32>, xQ: vec4<f32>, p: vec3<f32>) -> vec3<f32> {
	var dp = MulQuatVector(xQ, p);
return dp+(xP);
}

//////// import: "slmath-vector2.go"

//////// import: "slmath-vector3.go"
fn Length3(v: vec3<f32>) -> f32 {
	return sqrt(v.x*v.x + v.y*v.y + v.z*v.z);
}
fn Cross3(v: vec3<f32>,o: vec3<f32>) -> vec3<f32> {
	return vec3<f32>(v.y*o.z-v.z*o.y, v.z*o.x-v.x*o.z, v.x*o.y-v.y*o.x);
}

//////// import: "step.go"

//////// import: "step_body.go"

//////// import: "step_joint.go"