// Code generated by "gosl"; DO NOT EDIT
// kernel: CollisionBroad

// // Params are global parameters. 
@group(0) @binding(0)
var<storage, read> TensorStrides: array<u32>;
@group(0) @binding(1)
var<storage, read> Params: array<PhysParams>;
// // Bodies are the rigid body elements (dynamic and static), // specifying the constant, non-dynamic properties, // which is initial state for dynamics. // [body][BodyVarsN] 
@group(1) @binding(4)
var<storage, read_write> BodyCollidePairs: array<i32>;
// // Dynamics are the dynamic rigid body elements: these actually move. // Two alternating states are used: Params.Cur and Params.Next. // [dyn body][cur/next][DynamicVarsN] 
// // JointControls are dynamic joint control inputs, per joint DoF // (in correspondence with [JointDoFs]). This can be uploaded to the // GPU at every step. // [dof][JointControlVarsN] 

alias GPUVars = i32;

@compute @workgroup_size(64, 1, 1)
fn main(@builtin(workgroup_id) wgid: vec3<u32>, @builtin(num_workgroups) nwg: vec3<u32>, @builtin(local_invocation_index) loci: u32) {
	let idx = loci + (wgid.x + wgid.y * nwg.x + wgid.z * nwg.x * nwg.y) * 64;
	CollisionBroad(idx);
}

fn Index2D(s0: u32, s1: u32, i0: u32, i1: u32) -> u32 {
	return s0 * i0 + s1 * i1;
}


//////// import: "vars.go"

//////// import: "body.go"
alias BodyVars = i32; //enums:enum
const  BodyShape: BodyVars = 0;
const  BodyDynamic: BodyVars = 1;
const  BodyWorld: BodyVars = 2;
const  BodyGroup: BodyVars = 3;
const  BodySizeX: BodyVars = 4;
const  BodySizeY: BodyVars = 5;
const  BodySizeZ: BodyVars = 6;
const  BodyMass: BodyVars = 7;
const  BodyInvMass: BodyVars = 8;
const  BodyBounce: BodyVars = 9;
const  BodyFriction: BodyVars = 10;
const  BodyPosX: BodyVars = 11;
const  BodyPosY: BodyVars = 12;
const  BodyPosZ: BodyVars = 13;
const  BodyQuatX: BodyVars = 14;
const  BodyQuatY: BodyVars = 15;
const  BodyQuatZ: BodyVars = 16;
const  BodyQuatW: BodyVars = 17;
const  BodyComX: BodyVars = 18;
const  BodyComY: BodyVars = 19;
const  BodyComZ: BodyVars = 20;
const  BodyInertiaXX: BodyVars = 21;
const  BodyInertiaYX: BodyVars = 22;
const  BodyInertiaZX: BodyVars = 23;
const  BodyInertiaXY: BodyVars = 24;
const  BodyInertiaYY: BodyVars = 25;
const  BodyInertiaZY: BodyVars = 26;
const  BodyInertiaXZ: BodyVars = 27;
const  BodyInertiaYZ: BodyVars = 28;
const  BodyInertiaZZ: BodyVars = 29;
const  BodyInvInertiaXX: BodyVars = 30;
const  BodyInvInertiaYX: BodyVars = 31;
const  BodyInvInertiaZX: BodyVars = 32;
const  BodyInvInertiaXY: BodyVars = 33;
const  BodyInvInertiaYY: BodyVars = 34;
const  BodyInvInertiaZY: BodyVars = 35;
const  BodyInvInertiaXZ: BodyVars = 36;
const  BodyInvInertiaYZ: BodyVars = 37;
const  BodyInvInertiaZZ: BodyVars = 38;

//////// import: "contact.go"
alias ContactVars = i32; //enums:enum
const  ContactA: ContactVars = 0;
const  ContactB: ContactVars = 1;
const  ContactAPointX: ContactVars = 2;
const  ContactAPointY: ContactVars = 3;
const  ContactAPointZ: ContactVars = 4;
const  ContactBPointX: ContactVars = 5;
const  ContactBPointY: ContactVars = 6;
const  ContactBPointZ: ContactVars = 7;
const  ContactADepth: ContactVars = 8;
const  ContactBDepth: ContactVars = 9;
const  ContactNormX: ContactVars = 10;
const  ContactNormY: ContactVars = 11;
const  ContactNormZ: ContactVars = 12;
const  ContactForceX: ContactVars = 13;
const  ContactForceY: ContactVars = 14;
const  ContactForceZ: ContactVars = 15;
fn CollisionBroad(i: u32) { //gosl:kernel
let params = Params[0];; var ci = i32(i);; if (ci >= params.BodyCollidePairsN) {
	return;
}; var ba = BodyCollidePairs[Index2D(TensorStrides[40], TensorStrides[41], u32(ci), u32(0))];; var bb = BodyCollidePairs[Index2D(TensorStrides[40], TensorStrides[41],
u32(ci), u32(1))];; _ = ba;; _ = bb; }

//////// import: "control.go"
alias JointControlVars = i32; //enums:enum
const  JointControlForce: JointControlVars = 0;
const  JointTargetPos: JointControlVars    = 1;
const  JointTargetVel: JointControlVars = 2;

//////// import: "dynamics.go"
alias DynamicVars = i32; //enums:enum
const  DynBody: DynamicVars = 0;
const  DynPosX: DynamicVars = 1;
const  DynPosY: DynamicVars = 2;
const  DynPosZ: DynamicVars = 3;
const  DynQuatX: DynamicVars = 4;
const  DynQuatY: DynamicVars = 5;
const  DynQuatZ: DynamicVars = 6;
const  DynQuatW: DynamicVars = 7;
const  DynVelX: DynamicVars = 8;
const  DynVelY: DynamicVars = 9;
const  DynVelZ: DynamicVars = 10;
const  DynAngVelX: DynamicVars = 11;
const  DynAngVelY: DynamicVars = 12;
const  DynAngVelZ: DynamicVars = 13;
const  DynAccX: DynamicVars = 14;
const  DynAccY: DynamicVars = 15;
const  DynAccZ: DynamicVars = 16;
const  DynAngAccX: DynamicVars = 17;
const  DynAngAccY: DynamicVars = 18;
const  DynAngAccZ: DynamicVars = 19;
const  DynForceX: DynamicVars = 20;
const  DynForceY: DynamicVars = 21;
const  DynForceZ: DynamicVars = 22;
const  DynTorqueX: DynamicVars = 23;
const  DynTorqueY: DynamicVars = 24;
const  DynTorqueZ: DynamicVars = 25;
const  DynDeltaX: DynamicVars = 26;
const  DynDeltaY: DynamicVars = 27;
const  DynDeltaZ: DynamicVars = 28;
const  DynAngDeltaX: DynamicVars = 29;
const  DynAngDeltaY: DynamicVars = 30;
const  DynAngDeltaZ: DynamicVars = 31;

//////// import: "enumgen.go"
const BodyVarsN: BodyVars = 39;
const ContactVarsN: ContactVars = 16;
const JointControlVarsN: JointControlVars = 3;
const DynamicVarsN: DynamicVars = 32;
const GPUVarsN: GPUVars = 9;
const JointTypesN: JointTypes = 7;
const JointVarsN: JointVars = 50;
const JointDoFVarsN: JointDoFVars = 7;
const ShapesN: Shapes = 4;

//////// import: "joint.go"
const JointLimitUnlimited = 1e10;
alias JointTypes = i32; //enums:enum
const  Prismatic: JointTypes = 0;
const  Revolute: JointTypes = 1;
const  Ball: JointTypes = 2;
const  Fixed: JointTypes = 3;
const  Free: JointTypes = 4;
const  Distance: JointTypes = 5;
const  D6: JointTypes = 6;
alias JointVars = i32; //enums:enum
const  JointType: JointVars = 0;
const  JointEnabled: JointVars = 1;
const  JointParent: JointVars = 2;
const  JointChild: JointVars = 3;
const  JointPPosX: JointVars = 4;
const  JointPPosY: JointVars = 5;
const  JointPPosZ: JointVars = 6;
const  JointPQuatX: JointVars = 7;
const  JointPQuatY: JointVars = 8;
const  JointPQuatZ: JointVars = 9;
const  JointPQuatW: JointVars = 10;
const  JointCPosX: JointVars = 11;
const  JointCPosY: JointVars = 12;
const  JointCPosZ: JointVars = 13;
const  JointCQuatX: JointVars = 14;
const  JointCQuatY: JointVars = 15;
const  JointCQuatZ: JointVars = 16;
const  JointCQuatW: JointVars = 17;
const  JointLinearDoFN: JointVars = 18;
const  JointAngularDoFN: JointVars = 19;
const  JointDoF1: JointVars = 20;
const  JointDoF2: JointVars = 21;
const  JointDoF3: JointVars = 22;
const  JointDoF4: JointVars = 23;
const  JointDoF5: JointVars = 24;
const  JointDoF6: JointVars = 25;
const  JointPForceX: JointVars = 26;
const  JointPForceY: JointVars = 27;
const  JointPForceZ: JointVars = 28;
const  JointPTorqueX: JointVars = 29;
const  JointPTorqueY: JointVars = 30;
const  JointPTorqueZ: JointVars = 31;
const  JointCForceX: JointVars = 32;
const  JointCForceY: JointVars = 33;
const  JointCForceZ: JointVars = 34;
const  JointCTorqueX: JointVars = 35;
const  JointCTorqueY: JointVars = 36;
const  JointCTorqueZ: JointVars = 37;
const  JointPDeltaX: JointVars = 38;
const  JointPDeltaY: JointVars = 39;
const  JointPDeltaZ: JointVars = 40;
const  JointPAngDeltaX: JointVars = 41;
const  JointPAngDeltaY: JointVars = 42;
const  JointPAngDeltaZ: JointVars = 43;
const  JointCDeltaX: JointVars = 44;
const  JointCDeltaY: JointVars = 45;
const  JointCDeltaZ: JointVars = 46;
const  JointCAngDeltaX: JointVars = 47;
const  JointCAngDeltaY: JointVars = 48;
const  JointCAngDeltaZ: JointVars = 49;
alias JointDoFVars = i32; //enums:enum
const  JointAxisX: JointDoFVars = 0;
const  JointAxisY: JointDoFVars = 1;
const  JointAxisZ: JointDoFVars = 2;
const  JointLimitLower: JointDoFVars = 3;
const  JointLimitUpper: JointDoFVars = 4;
const  JointStiff: JointDoFVars = 5;
const  JointDamp: JointDoFVars = 6;

//////// import: "params.go"
struct PhysParams {
	Iterations: i32,
	Dt: f32,
	SoftRelax: f32,
	JointLinearRelax: f32,
	JointAngularRelax: f32,
	JointLinearComply: f32,
	JointAngularComply: f32,
	ContactRelax: f32,
	AngularDamping: f32,
	ContactWeighting: i32,
	Restitution: i32,
	Cur: i32,
	Next: i32,
	BodiesN: i32,
	DynamicsN: i32,
	JointsN: i32,
	JointDoFsN: i32,
	BodyJointsMax: i32,
	BodyCollidePairsN: i32,
	pad: i32,
	Gravity: vec4<f32>,
}

//////// import: "shapes.go"
alias Shapes = i32; //enums:enum
const  Box: Shapes = 0;
const  Sphere: Shapes = 1;
const  Cylinder: Shapes = 2;
const  Capsule: Shapes = 3;

//////// import: "slmath-matrix3.go"

//////// import: "slmath-quaternion.go"

//////// import: "slmath-vector3.go"

//////// import: "step.go"

//////// import: "step_body.go"

//////// import: "step_joint.go"