// Code generated by "gosl"; DO NOT EDIT
// kernel: DeltasFromContacts

// // Params are global parameters. 
@group(0) @binding(0)
var<storage, read> TensorStrides: array<u32>;
@group(0) @binding(1)
var<storage, read> Params: array<PhysParams>;
// // Bodies are the rigid body elements (dynamic and static), // specifying the constant, non-dynamic properties, // which is initial state for dynamics. // [body][BodyVarsN] 
// // Dynamics are the dynamic rigid body elements: these actually move. // Two alternating states are used: Params.Cur and Params.Next. // [dyn body][cur/next][DynamicVarsN] 
@group(2) @binding(0)
var<storage, read_write> Dynamics: array<f32>;
@group(2) @binding(3)
var<storage, read_write> ContactsN: array<i32>;
@group(2) @binding(4)
var<storage, read_write> Contacts: array<f32>;
// // JointControls are dynamic joint control inputs, per joint DoF // (in correspondence with [JointDoFs]). This can be uploaded to the // GPU at every step. // [dof][JointControlVarsN] 

alias GPUVars = i32;

@compute @workgroup_size(64, 1, 1)
fn main(@builtin(workgroup_id) wgid: vec3<u32>, @builtin(num_workgroups) nwg: vec3<u32>, @builtin(local_invocation_index) loci: u32) {
	let idx = loci + (wgid.x + wgid.y * nwg.x + wgid.z * nwg.x * nwg.y) * 64;
	DeltasFromContacts(idx);
}

fn Index3D(s0: u32, s1: u32, s2: u32, i0: u32, i1: u32, i2: u32) -> u32 {
	return s0 * i0 + s1 * i1 + s2 * i2;
}

fn Index1D(s0: u32, i0: u32) -> u32 {
	return s0 * i0;
}

fn Index2D(s0: u32, s1: u32, i0: u32, i1: u32) -> u32 {
	return s0 * i0 + s1 * i1;
}


//////// import: "vars.go"

//////// import: "body.go"
alias BodyVars = i32; //enums:enum
const  BodyShape: BodyVars = 0;
const  BodyDynamic: BodyVars = 1;
const  BodyWorld: BodyVars = 2;
const  BodyGroup: BodyVars = 3;
const  BodyHSizeX: BodyVars = 4;
const  BodyHSizeY: BodyVars = 5;
const  BodyHSizeZ: BodyVars = 6;
const  BodyThick: BodyVars = 7;
const  BodyMass: BodyVars = 8;
const  BodyInvMass: BodyVars = 9;
const  BodyBounce: BodyVars = 10;
const  BodyFriction: BodyVars = 11;
const  BodyFrictionTortion: BodyVars = 12;
const  BodyFrictionRolling: BodyVars = 13;
const  BodyPosX: BodyVars = 14;
const  BodyPosY: BodyVars = 15;
const  BodyPosZ: BodyVars = 16;
const  BodyQuatX: BodyVars = 17;
const  BodyQuatY: BodyVars = 18;
const  BodyQuatZ: BodyVars = 19;
const  BodyQuatW: BodyVars = 20;
const  BodyComX: BodyVars = 21;
const  BodyComY: BodyVars = 22;
const  BodyComZ: BodyVars = 23;
const  BodyInertiaXX: BodyVars = 24;
const  BodyInertiaYX: BodyVars = 25;
const  BodyInertiaZX: BodyVars = 26;
const  BodyInertiaXY: BodyVars = 27;
const  BodyInertiaYY: BodyVars = 28;
const  BodyInertiaZY: BodyVars = 29;
const  BodyInertiaXZ: BodyVars = 30;
const  BodyInertiaYZ: BodyVars = 31;
const  BodyInertiaZZ: BodyVars = 32;
const  BodyInvInertiaXX: BodyVars = 33;
const  BodyInvInertiaYX: BodyVars = 34;
const  BodyInvInertiaZX: BodyVars = 35;
const  BodyInvInertiaXY: BodyVars = 36;
const  BodyInvInertiaYY: BodyVars = 37;
const  BodyInvInertiaZY: BodyVars = 38;
const  BodyInvInertiaXZ: BodyVars = 39;
const  BodyInvInertiaYZ: BodyVars = 40;
const  BodyInvInertiaZZ: BodyVars = 41;
const  BodyRadius: BodyVars = 42;

//////// import: "contact.go"
alias ContactVars = i32; //enums:enum
const  ContactA: ContactVars = 0;
const  ContactB: ContactVars = 1;
const  ContactPointIdx: ContactVars = 2;
const  ContactAPointX: ContactVars = 3;
const  ContactAPointY: ContactVars = 4;
const  ContactAPointZ: ContactVars = 5;
const  ContactBPointX: ContactVars = 6;
const  ContactBPointY: ContactVars = 7;
const  ContactBPointZ: ContactVars = 8;
const  ContactAOffX: ContactVars = 9;
const  ContactAOffY: ContactVars = 10;
const  ContactAOffZ: ContactVars = 11;
const  ContactBOffX: ContactVars = 12;
const  ContactBOffY: ContactVars = 13;
const  ContactBOffZ: ContactVars = 14;
const  ContactAThick: ContactVars = 15;
const  ContactBThick: ContactVars = 16;
const  ContactNormX: ContactVars = 17;
const  ContactNormY: ContactVars = 18;
const  ContactNormZ: ContactVars = 19;
const  ContactWeight: ContactVars = 20;
const  ContactADeltaX: ContactVars = 21;
const  ContactADeltaY: ContactVars = 22;
const  ContactADeltaZ: ContactVars = 23;
const  ContactAAngDeltaX: ContactVars = 24;
const  ContactAAngDeltaY: ContactVars = 25;
const  ContactAAngDeltaZ: ContactVars = 26;
const  ContactBDeltaX: ContactVars = 27;
const  ContactBDeltaY: ContactVars = 28;
const  ContactBDeltaZ: ContactVars = 29;
const  ContactBAngDeltaX: ContactVars = 30;
const  ContactBAngDeltaY: ContactVars = 31;
const  ContactBAngDeltaZ: ContactVars = 32;
const BroadContactVarsN = ContactAPointX;
fn GetContactA(idx: i32) -> i32 { return i32(bitcast<u32>(Contacts[Index2D(TensorStrides[90], TensorStrides[91], u32(idx), u32(ContactA))])); }
fn GetContactB(idx: i32) -> i32 { return i32(bitcast<u32>(Contacts[Index2D(TensorStrides[90], TensorStrides[91], u32(idx), u32(ContactB))])); }
fn ContactADelta(idx: i32) -> vec3<f32> {
	return vec3<f32>(Contacts[Index2D(TensorStrides[90], TensorStrides[91], u32(idx), u32(ContactADeltaX))], Contacts[Index2D(TensorStrides[90], TensorStrides[91], u32(idx), u32(ContactADeltaY))], Contacts[Index2D(TensorStrides[90], TensorStrides[91], u32(idx), u32(ContactADeltaZ))]);
}
fn ContactAAngDelta(idx: i32) -> vec3<f32> {
	return vec3<f32>(Contacts[Index2D(TensorStrides[90], TensorStrides[91], u32(idx), u32(ContactAAngDeltaX))], Contacts[Index2D(TensorStrides[90], TensorStrides[91], u32(idx), u32(ContactAAngDeltaY))], Contacts[Index2D(TensorStrides[90], TensorStrides[91], u32(idx), u32(ContactAAngDeltaZ))]);
}
fn ContactBDelta(idx: i32) -> vec3<f32> {
	return vec3<f32>(Contacts[Index2D(TensorStrides[90], TensorStrides[91], u32(idx), u32(ContactBDeltaX))], Contacts[Index2D(TensorStrides[90], TensorStrides[91], u32(idx), u32(ContactBDeltaY))], Contacts[Index2D(TensorStrides[90], TensorStrides[91], u32(idx), u32(ContactBDeltaZ))]);
}
fn ContactBAngDelta(idx: i32) -> vec3<f32> {
	return vec3<f32>(Contacts[Index2D(TensorStrides[90], TensorStrides[91], u32(idx), u32(ContactBAngDeltaX))], Contacts[Index2D(TensorStrides[90], TensorStrides[91], u32(idx), u32(ContactBAngDeltaY))], Contacts[Index2D(TensorStrides[90], TensorStrides[91], u32(idx), u32(ContactBAngDeltaZ))]);
}
fn DeltasFromContacts(i: u32) { //gosl:kernel
	let params = Params[0];
	var di = i32(i);
	if (di >= params.DynamicsN) {
		return;
	}
	var cmax = ContactsN[0];
	var bi = DynamicBody(di);
	var td = DynamicDelta(di, params.Next);
	var ta = DynamicAngDelta(di, params.Next);
	var tw = f32(0);
	for (var ci=0; ci<cmax; ci++) {
		var wt = Contacts[Index2D(TensorStrides[90], TensorStrides[91], u32(ci), u32(ContactWeight))];
		if (wt == 0) {
			continue;
		}
		var biA = GetContactA(ci);
		var biB = GetContactB(ci);
		if (biA == bi) {
			tw += wt;
			var d = ContactADelta(ci);
			td = td+(d);
			var a = ContactAAngDelta(ci);
			ta = ta+(a);
		}
		if (biB == bi) {
			tw += wt;
			var d = ContactBDelta(ci);
			td = td+(d);
			var a = ContactBAngDelta(ci);
			ta = ta+(a);
		}
	}
	SetDynamicDelta(di, params.Next, td);
	SetDynamicAngDelta(di, params.Next, ta);
	Dynamics[Index3D(TensorStrides[50], TensorStrides[51], TensorStrides[52], u32(di), u32(params.Next), u32(DynContactWeight))] = tw;
}

//////// import: "control.go"
alias JointControlVars = i32; //enums:enum
const  JointControlForce: JointControlVars = 0;
const  JointTargetPos: JointControlVars    = 1;
const  JointTargetVel: JointControlVars = 2;

//////// import: "dynamics.go"
alias DynamicVars = i32; //enums:enum
const  DynBody: DynamicVars = 0;
const  DynPosX: DynamicVars = 1;
const  DynPosY: DynamicVars = 2;
const  DynPosZ: DynamicVars = 3;
const  DynQuatX: DynamicVars = 4;
const  DynQuatY: DynamicVars = 5;
const  DynQuatZ: DynamicVars = 6;
const  DynQuatW: DynamicVars = 7;
const  DynVelX: DynamicVars = 8;
const  DynVelY: DynamicVars = 9;
const  DynVelZ: DynamicVars = 10;
const  DynAngVelX: DynamicVars = 11;
const  DynAngVelY: DynamicVars = 12;
const  DynAngVelZ: DynamicVars = 13;
const  DynAccX: DynamicVars = 14;
const  DynAccY: DynamicVars = 15;
const  DynAccZ: DynamicVars = 16;
const  DynAngAccX: DynamicVars = 17;
const  DynAngAccY: DynamicVars = 18;
const  DynAngAccZ: DynamicVars = 19;
const  DynForceX: DynamicVars = 20;
const  DynForceY: DynamicVars = 21;
const  DynForceZ: DynamicVars = 22;
const  DynTorqueX: DynamicVars = 23;
const  DynTorqueY: DynamicVars = 24;
const  DynTorqueZ: DynamicVars = 25;
const  DynDeltaX: DynamicVars = 26;
const  DynDeltaY: DynamicVars = 27;
const  DynDeltaZ: DynamicVars = 28;
const  DynAngDeltaX: DynamicVars = 29;
const  DynAngDeltaY: DynamicVars = 30;
const  DynAngDeltaZ: DynamicVars = 31;
const  DynContactWeight: DynamicVars = 32;
fn DynamicBody(idx: i32) -> i32 { return i32(bitcast<u32>(Dynamics[Index3D(TensorStrides[50], TensorStrides[51], TensorStrides[52], u32(idx), u32(0), u32(DynBody))])); }
fn DynamicDelta(idx: i32,cni: i32) -> vec3<f32> {
	return vec3<f32>(Dynamics[Index3D(TensorStrides[50], TensorStrides[51], TensorStrides[52], u32(idx), u32(cni), u32(DynDeltaX))], Dynamics[Index3D(TensorStrides[50], TensorStrides[51], TensorStrides[52], u32(idx), u32(cni), u32(DynDeltaY))], Dynamics[Index3D(TensorStrides[50], TensorStrides[51], TensorStrides[52], u32(idx), u32(cni), u32(DynDeltaZ))]);
}
fn SetDynamicDelta(idx: i32,cni: i32, delta: vec3<f32>) {
	Dynamics[Index3D(TensorStrides[50], TensorStrides[51], TensorStrides[52], u32(idx), u32(cni), u32(DynDeltaX))] = delta.x;
	Dynamics[Index3D(TensorStrides[50], TensorStrides[51], TensorStrides[52], u32(idx), u32(cni), u32(DynDeltaY))] = delta.y;
	Dynamics[Index3D(TensorStrides[50], TensorStrides[51], TensorStrides[52], u32(idx), u32(cni), u32(DynDeltaZ))] = delta.z;
}
fn DynamicAngDelta(idx: i32,cni: i32) -> vec3<f32> {
	return vec3<f32>(Dynamics[Index3D(TensorStrides[50], TensorStrides[51], TensorStrides[52], u32(idx), u32(cni), u32(DynAngDeltaX))], Dynamics[Index3D(TensorStrides[50], TensorStrides[51], TensorStrides[52], u32(idx), u32(cni), u32(DynAngDeltaY))], Dynamics[Index3D(TensorStrides[50], TensorStrides[51], TensorStrides[52], u32(idx), u32(cni), u32(DynAngDeltaZ))]);
}
fn SetDynamicAngDelta(idx: i32,cni: i32, angDelta: vec3<f32>) {
	Dynamics[Index3D(TensorStrides[50], TensorStrides[51], TensorStrides[52], u32(idx), u32(cni), u32(DynAngDeltaX))] = angDelta.x;
	Dynamics[Index3D(TensorStrides[50], TensorStrides[51], TensorStrides[52], u32(idx), u32(cni), u32(DynAngDeltaY))] = angDelta.y;
	Dynamics[Index3D(TensorStrides[50], TensorStrides[51], TensorStrides[52], u32(idx), u32(cni), u32(DynAngDeltaZ))] = angDelta.z;
}

//////// import: "enumgen.go"
const BodyVarsN: BodyVars = 43;
const ContactVarsN: ContactVars = 33;
const JointControlVarsN: JointControlVars = 3;
const DynamicVarsN: DynamicVars = 33;
const GPUVarsN: GPUVars = 12;
const JointTypesN: JointTypes = 7;
const JointVarsN: JointVars = 50;
const JointDoFVarsN: JointDoFVars = 7;
const ShapesN: Shapes = 6;

//////// import: "joint.go"
const JointLimitUnlimited = 1e10;
alias JointTypes = i32; //enums:enum
const  Prismatic: JointTypes = 0;
const  Revolute: JointTypes = 1;
const  Ball: JointTypes = 2;
const  Fixed: JointTypes = 3;
const  Free: JointTypes = 4;
const  Distance: JointTypes = 5;
const  D6: JointTypes = 6;
alias JointVars = i32; //enums:enum
const  JointType: JointVars = 0;
const  JointEnabled: JointVars = 1;
const  JointParent: JointVars = 2;
const  JointChild: JointVars = 3;
const  JointPPosX: JointVars = 4;
const  JointPPosY: JointVars = 5;
const  JointPPosZ: JointVars = 6;
const  JointPQuatX: JointVars = 7;
const  JointPQuatY: JointVars = 8;
const  JointPQuatZ: JointVars = 9;
const  JointPQuatW: JointVars = 10;
const  JointCPosX: JointVars = 11;
const  JointCPosY: JointVars = 12;
const  JointCPosZ: JointVars = 13;
const  JointCQuatX: JointVars = 14;
const  JointCQuatY: JointVars = 15;
const  JointCQuatZ: JointVars = 16;
const  JointCQuatW: JointVars = 17;
const  JointLinearDoFN: JointVars = 18;
const  JointAngularDoFN: JointVars = 19;
const  JointDoF1: JointVars = 20;
const  JointDoF2: JointVars = 21;
const  JointDoF3: JointVars = 22;
const  JointDoF4: JointVars = 23;
const  JointDoF5: JointVars = 24;
const  JointDoF6: JointVars = 25;
const  JointPForceX: JointVars = 26;
const  JointPForceY: JointVars = 27;
const  JointPForceZ: JointVars = 28;
const  JointPTorqueX: JointVars = 29;
const  JointPTorqueY: JointVars = 30;
const  JointPTorqueZ: JointVars = 31;
const  JointCForceX: JointVars = 32;
const  JointCForceY: JointVars = 33;
const  JointCForceZ: JointVars = 34;
const  JointCTorqueX: JointVars = 35;
const  JointCTorqueY: JointVars = 36;
const  JointCTorqueZ: JointVars = 37;
const  JointPDeltaX: JointVars = 38;
const  JointPDeltaY: JointVars = 39;
const  JointPDeltaZ: JointVars = 40;
const  JointPAngDeltaX: JointVars = 41;
const  JointPAngDeltaY: JointVars = 42;
const  JointPAngDeltaZ: JointVars = 43;
const  JointCDeltaX: JointVars = 44;
const  JointCDeltaY: JointVars = 45;
const  JointCDeltaZ: JointVars = 46;
const  JointCAngDeltaX: JointVars = 47;
const  JointCAngDeltaY: JointVars = 48;
const  JointCAngDeltaZ: JointVars = 49;
alias JointDoFVars = i32; //enums:enum
const  JointAxisX: JointDoFVars = 0;
const  JointAxisY: JointDoFVars = 1;
const  JointAxisZ: JointDoFVars = 2;
const  JointLimitLower: JointDoFVars = 3;
const  JointLimitUpper: JointDoFVars = 4;
const  JointStiff: JointDoFVars = 5;
const  JointDamp: JointDoFVars = 6;

//////// import: "params.go"
struct PhysParams {
	Iterations: i32,
	Dt: f32,
	SoftRelax: f32,
	JointLinearRelax: f32,
	JointAngularRelax: f32,
	JointLinearComply: f32,
	JointAngularComply: f32,
	ContactRelax: f32,
	AngularDamping: f32,
	ContactWeighting: i32,
	Restitution: i32,
	MaxGeomIter: i32,
	ContactMargin: f32,
	ContactsMax: i32,
	Cur: i32,
	Next: i32,
	BodiesN: i32,
	DynamicsN: i32,
	JointsN: i32,
	JointDoFsN: i32,
	BodyJointsMax: i32,
	BodyCollidePairsN: i32,
	pad: i32,
	pad1: i32,
	Gravity: vec4<f32>,
}

//////// import: "shapecollide.go"
struct GeomData {
	BodyIdx: i32,
	Shape: Shapes,
	MinSize: f32,
	Thick: f32,
	Radius: f32,
	Size: vec3<f32>,
	WbR: vec3<f32>,
	WbQ: vec4<f32>,
	BwR: vec3<f32>,
	BwQ: vec4<f32>,
}

//////// import: "shapegeom.go"

//////// import: "shapes.go"
alias Shapes = i32; //enums:enum
const  Plane: Shapes = 0;
const  Sphere: Shapes = 1;
const  Capsule: Shapes = 2;
const  Cylinder: Shapes = 3;
const  Box: Shapes = 4;
const  Cone: Shapes = 5;

//////// import: "slmath-matrix3.go"

//////// import: "slmath-quaternion.go"

//////// import: "slmath-vector2.go"

//////// import: "slmath-vector3.go"

//////// import: "step.go"

//////// import: "step_body.go"

//////// import: "step_joint.go"