// Code generated by "gosl"; DO NOT EDIT
// kernel: InitDynamics

// // Params are global parameters. 
@group(0) @binding(0)
var<storage, read> TensorStrides: array<u32>;
@group(0) @binding(1)
var<storage, read> Params: array<PhysParams>;
// // Bodies are the rigid body elements (dynamic and static), // specifying the constant, non-dynamic properties, // which is initial state for dynamics. // [body][BodyVarsN] 
@group(1) @binding(0)
var<storage, read_write> Bodies: array<f32>;
// // Dynamics are the dynamic rigid body elements: these actually move. // [dyn body][DynamicVarsN] 
@group(2) @binding(0)
var<storage, read_write> Dynamics: array<f32>;
// // JointControls are dynamic joint control inputs. // [joint][JointControlVarsN] 

alias GPUVars = i32;

@compute @workgroup_size(64, 1, 1)
fn main(@builtin(workgroup_id) wgid: vec3<u32>, @builtin(num_workgroups) nwg: vec3<u32>, @builtin(local_invocation_index) loci: u32) {
	let idx = loci + (wgid.x + wgid.y * nwg.x + wgid.z * nwg.x * nwg.y) * 64;
	InitDynamics(idx);
}

fn Index2D(s0: u32, s1: u32, i0: u32, i1: u32) -> u32 {
	return s0 * i0 + s1 * i1;
}


//////// import: "vars.go"

//////// import: "body.go"
alias BodyVars = i32; //enums:enum
const  BodyShape: BodyVars = 0;
const  BodyWorldIndex: BodyVars = 1;
const  BodySizeX: BodyVars = 2;
const  BodySizeY: BodyVars = 3;
const  BodySizeZ: BodyVars = 4;
const  BodyMass: BodyVars = 5;
const  BodyInvMass: BodyVars = 6;
const  BodyBounce: BodyVars = 7;
const  BodyFriction: BodyVars = 8;
const  BodyPosX: BodyVars = 9;
const  BodyPosY: BodyVars = 10;
const  BodyPosZ: BodyVars = 11;
const  BodyRotX: BodyVars = 12;
const  BodyRotY: BodyVars = 13;
const  BodyRotZ: BodyVars = 14;
const  BodyRotW: BodyVars = 15;
const  BodyComX: BodyVars = 16;
const  BodyComY: BodyVars = 17;
const  BodyComZ: BodyVars = 18;
const  BodyInertiaXX: BodyVars = 19;
const  BodyInertiaYX: BodyVars = 20;
const  BodyInertiaZX: BodyVars = 21;
const  BodyInertiaXY: BodyVars = 22;
const  BodyInertiaYY: BodyVars = 23;
const  BodyInertiaZY: BodyVars = 24;
const  BodyInertiaXZ: BodyVars = 25;
const  BodyInertiaYZ: BodyVars = 26;
const  BodyInertiaZZ: BodyVars = 27;
const  BodyInvInertiaXX: BodyVars = 28;
const  BodyInvInertiaYX: BodyVars = 29;
const  BodyInvInertiaZX: BodyVars = 30;
const  BodyInvInertiaXY: BodyVars = 31;
const  BodyInvInertiaYY: BodyVars = 32;
const  BodyInvInertiaZY: BodyVars = 33;
const  BodyInvInertiaXZ: BodyVars = 34;
const  BodyInvInertiaYZ: BodyVars = 35;
const  BodyInvInertiaZZ: BodyVars = 36;
alias DynamicVars = i32; //enums:enum
const  DynIndex: DynamicVars = 0;
const  DynPosX: DynamicVars = 1;
const  DynPosY: DynamicVars = 2;
const  DynPosZ: DynamicVars = 3;
const  DynRotX: DynamicVars = 4;
const  DynRotY: DynamicVars = 5;
const  DynRotZ: DynamicVars = 6;
const  DynRotW: DynamicVars = 7;
const  DynVelX: DynamicVars = 8;
const  DynVelY: DynamicVars = 9;
const  DynVelZ: DynamicVars = 10;
const  DynAngVelX: DynamicVars = 11;
const  DynAngVelY: DynamicVars = 12;
const  DynAngVelZ: DynamicVars = 13;
const  DynAccX: DynamicVars = 14;
const  DynAccY: DynamicVars = 15;
const  DynAccZ: DynamicVars = 16;
const  DynAngAccX: DynamicVars = 17;
const  DynAngAccY: DynamicVars = 18;
const  DynAngAccZ: DynamicVars = 19;
const  DynForceX: DynamicVars = 20;
const  DynForceY: DynamicVars = 21;
const  DynForceZ: DynamicVars = 22;
const  DynTorqueX: DynamicVars = 23;
const  DynTorqueY: DynamicVars = 24;
const  DynTorqueZ: DynamicVars = 25;
const  DynDeltaX: DynamicVars = 26;
const  DynDeltaY: DynamicVars = 27;
const  DynDeltaZ: DynamicVars = 28;
const  DynAngDeltaX: DynamicVars = 29;
const  DynAngDeltaY: DynamicVars = 30;
const  DynAngDeltaZ: DynamicVars = 31;
fn DynamicIndex(idx: i32) -> i32 {
	return i32(bitcast<u32>(Dynamics[Index2D(TensorStrides[30], TensorStrides[31], u32(idx), u32(DynIndex))]));
}

//////// import: "contact.go"
alias ContactVars = i32; //enums:enum
const  ContactA: ContactVars = 0;
const  ContactB: ContactVars = 1;
const  ContactNormX: ContactVars = 2;
const  ContactNormY: ContactVars = 3;
const  ContactNormZ: ContactVars = 4;
const  ContactPointX: ContactVars = 5;
const  ContactPointY: ContactVars = 6;
const  ContactPointZ: ContactVars = 7;
const  ContactDist: ContactVars = 8;

//////// import: "control.go"
alias JointControlVars = i32; //enums:enum
const  JointForceX: JointControlVars = 0;
const  JointForceY: JointControlVars = 1;
const  JointForceZ: JointControlVars = 2;
const  JointTorqueX: JointControlVars = 3;
const  JointTorqueY: JointControlVars = 4;
const  JointTorqueZ: JointControlVars = 5;
const  JointTargetPosX: JointControlVars = 6;
const  JointTargetPosY: JointControlVars = 7;
const  JointTargetPosZ: JointControlVars = 8;
const  JointTargetRotX: JointControlVars = 9;
const  JointTargetRotY: JointControlVars = 10;
const  JointTargetRotZ: JointControlVars = 11;
const  JointTargetRotW: JointControlVars = 12;
const  JointTargetVelX: JointControlVars = 13;
const  JointTargetVelY: JointControlVars = 14;
const  JointTargetVelZ: JointControlVars = 15;
const  JointTargetAngVelX: JointControlVars = 16;
const  JointTargetAngVelY: JointControlVars = 17;
const  JointTargetAngVelZ: JointControlVars = 18;

//////// import: "enumgen.go"
const BodyVarsN: BodyVars = 37;
const DynamicVarsN: DynamicVars = 32;
const ContactVarsN: ContactVars = 9;
const JointControlVarsN: JointControlVars = 19;
const GPUVarsN: GPUVars = 7;
const JointVarsN: JointVars = 35;
const JointTypesN: JointTypes = 7;
const ShapesN: Shapes = 4;

//////// import: "joint.go"
alias JointVars = i32; //enums:enum
const  JointType: JointVars = 0;
const  JointEnabled: JointVars = 1;
const  JointParent: JointVars = 2;
const  JointChild: JointVars = 3;
const  JointPPosX: JointVars = 4;
const  JointPPosY: JointVars = 5;
const  JointPPosZ: JointVars = 6;
const  JointPRotX: JointVars = 7;
const  JointPRotY: JointVars = 8;
const  JointPRotZ: JointVars = 9;
const  JointPRotW: JointVars = 10;
const  JointCPosX: JointVars = 11;
const  JointCPosY: JointVars = 12;
const  JointCPosZ: JointVars = 13;
const  JointCRotX: JointVars = 14;
const  JointCRotY: JointVars = 15;
const  JointCRotZ: JointVars = 16;
const  JointCRotW: JointVars = 17;
const  JointAxisX: JointVars = 18;
const  JointAxisY: JointVars = 19;
const  JointAxisZ: JointVars = 20;
const  JointLimitLower: JointVars = 21;
const  JointLimitUpper: JointVars = 22;
const  JointPForceX: JointVars = 23;
const  JointPForceY: JointVars = 24;
const  JointPForceZ: JointVars = 25;
const  JointPTorqueX: JointVars = 26;
const  JointPTorqueY: JointVars = 27;
const  JointPTorqueZ: JointVars = 28;
const  JointCForceX: JointVars = 29;
const  JointCForceY: JointVars = 30;
const  JointCForceZ: JointVars = 31;
const  JointCTorqueX: JointVars = 32;
const  JointCTorqueY: JointVars = 33;
const  JointCTorqueZ: JointVars = 34;
alias JointTypes = i32; //enums:enum
const  Prismatic: JointTypes = 0;
const  Revolute: JointTypes = 1;
const  Ball: JointTypes = 2;
const  Fixed: JointTypes = 3;
const  Free: JointTypes = 4;
const  Distance: JointTypes = 5;
const  D6: JointTypes = 6;

//////// import: "params.go"
struct PhysParams {
	DynamicsN: i32,
	JointsN: i32,
	Iters: i32,
	Dt: f32,
	SoftRelax: f32,
	JointLinearRelax: f32,
	JointAngularRelax: f32,
	JointLinearComply: f32,
	JointAngularComply: f32,
	ContactRelax: f32,
	AngularDamping: f32,
	ContactWeighting: i32,
	Restitution: i32,
	pad: f32,
	pad1: f32,
	pad2: f32,
	Gravity: vec4<f32>,
}

//////// import: "shapes.go"
alias Shapes = i32; //enums:enum
const  Box: Shapes = 0;
const  Sphere: Shapes = 1;
const  Cylinder: Shapes = 2;
const  Capsule: Shapes = 3;

//////// import: "slmath-matrix3.go"

//////// import: "slmath-quaternion.go"

//////// import: "slmath-vector3.go"

//////// import: "step.go"
fn InitDynamics(i: u32) { //gosl:kernel
	let pars = Params[0];
	var ii = i32(i);
	if (ii >= pars.DynamicsN) {
		return;
	}
	var bi = DynamicIndex(ii);
	Dynamics[Index2D(TensorStrides[30], TensorStrides[31], u32(ii), u32(DynPosX))] = Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(bi), u32(BodyPosX))];
	Dynamics[Index2D(TensorStrides[30], TensorStrides[31], u32(ii), u32(DynPosY))] = Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(bi), u32(BodyPosY))];
	Dynamics[Index2D(TensorStrides[30], TensorStrides[31], u32(ii), u32(DynPosZ))] = Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(bi), u32(BodyPosZ))];
	Dynamics[Index2D(TensorStrides[30], TensorStrides[31], u32(ii), u32(DynRotX))] = Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(bi), u32(BodyRotX))];
	Dynamics[Index2D(TensorStrides[30], TensorStrides[31], u32(ii), u32(DynRotY))] = Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(bi), u32(BodyRotY))];
	Dynamics[Index2D(TensorStrides[30], TensorStrides[31], u32(ii), u32(DynRotZ))] = Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(bi), u32(BodyRotZ))];
	Dynamics[Index2D(TensorStrides[30], TensorStrides[31], u32(ii), u32(DynRotW))] = Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(bi), u32(BodyRotW))];
	for (var v = DynVelX; v < DynamicVarsN; v++) {
		Dynamics[Index2D(TensorStrides[30], TensorStrides[31],
		u32(ii), u32(v))] = 0.0;
	}
}