// Code generated by "gosl"; DO NOT EDIT
// kernel: StepSolveJoints

// // Params are global parameters. 
@group(0) @binding(0)
var<storage, read> TensorStrides: array<u32>;
@group(0) @binding(1)
var<storage, read> Params: array<PhysParams>;
// // Bodies are the rigid body elements (dynamic and static), // specifying the constant, non-dynamic properties, // which is initial state for dynamics. // [body][BodyVarsN] 
@group(1) @binding(0)
var<storage, read_write> Bodies: array<f32>;
@group(1) @binding(1)
var<storage, read_write> Joints: array<f32>;
@group(1) @binding(2)
var<storage, read_write> JointDoFs: array<f32>;
// // Dynamics are the dynamic rigid body elements: these actually move. // Two alternating states are used: Params.Cur and Params.Next. // [dyn body][cur/next][DynamicVarsN] 
@group(2) @binding(0)
var<storage, read_write> Dynamics: array<f32>;
// // JointControls are dynamic joint control inputs, per joint DoF // (in correspondence with [JointDoFs]). This can be uploaded to the // GPU at every step. // [dof][JointControlVarsN] 
@group(3) @binding(0)
var<storage, read_write> JointControls: array<f32>;

alias GPUVars = i32;

@compute @workgroup_size(64, 1, 1)
fn main(@builtin(workgroup_id) wgid: vec3<u32>, @builtin(num_workgroups) nwg: vec3<u32>, @builtin(local_invocation_index) loci: u32) {
	let idx = loci + (wgid.x + wgid.y * nwg.x + wgid.z * nwg.x * nwg.y) * 64;
	StepSolveJoints(idx);
}

fn Index2D(s0: u32, s1: u32, i0: u32, i1: u32) -> u32 {
	return s0 * i0 + s1 * i1;
}

fn Index3D(s0: u32, s1: u32, s2: u32, i0: u32, i1: u32, i2: u32) -> u32 {
	return s0 * i0 + s1 * i1 + s2 * i2;
}


//////// import: "vars.go"

//////// import: "body.go"
alias BodyVars = i32; //enums:enum
const  BodyShape: BodyVars = 0;
const  BodyWorldIndex: BodyVars = 1;
const  BodySizeX: BodyVars = 2;
const  BodySizeY: BodyVars = 3;
const  BodySizeZ: BodyVars = 4;
const  BodyMass: BodyVars = 5;
const  BodyInvMass: BodyVars = 6;
const  BodyBounce: BodyVars = 7;
const  BodyFriction: BodyVars = 8;
const  BodyPosX: BodyVars = 9;
const  BodyPosY: BodyVars = 10;
const  BodyPosZ: BodyVars = 11;
const  BodyQuatX: BodyVars = 12;
const  BodyQuatY: BodyVars = 13;
const  BodyQuatZ: BodyVars = 14;
const  BodyQuatW: BodyVars = 15;
const  BodyComX: BodyVars = 16;
const  BodyComY: BodyVars = 17;
const  BodyComZ: BodyVars = 18;
const  BodyInertiaXX: BodyVars = 19;
const  BodyInertiaYX: BodyVars = 20;
const  BodyInertiaZX: BodyVars = 21;
const  BodyInertiaXY: BodyVars = 22;
const  BodyInertiaYY: BodyVars = 23;
const  BodyInertiaZY: BodyVars = 24;
const  BodyInertiaXZ: BodyVars = 25;
const  BodyInertiaYZ: BodyVars = 26;
const  BodyInertiaZZ: BodyVars = 27;
const  BodyInvInertiaXX: BodyVars = 28;
const  BodyInvInertiaYX: BodyVars = 29;
const  BodyInvInertiaZX: BodyVars = 30;
const  BodyInvInertiaXY: BodyVars = 31;
const  BodyInvInertiaYY: BodyVars = 32;
const  BodyInvInertiaZY: BodyVars = 33;
const  BodyInvInertiaXZ: BodyVars = 34;
const  BodyInvInertiaYZ: BodyVars = 35;
const  BodyInvInertiaZZ: BodyVars = 36;
fn BodyCom(idx: i32) -> vec3<f32> {
	return vec3<f32>(Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(idx), u32(BodyComX))], Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(idx), u32(BodyComY))], Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(idx), u32(BodyComZ))]);
}
fn BodyInvInertia(idx: i32) -> mat3x3f {
	return mat3x3f(Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(idx), u32(BodyInvInertiaXX))], Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(idx), u32(BodyInvInertiaYX))], Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(idx), u32(BodyInvInertiaZX))],
		Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(idx), u32(BodyInvInertiaXY))], Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(idx), u32(BodyInvInertiaYY))], Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(idx), u32(BodyInvInertiaZY))],
		Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(idx), u32(BodyInvInertiaXZ))], Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(idx), u32(BodyInvInertiaYZ))], Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(idx), u32(BodyInvInertiaZZ))]);
}

//////// import: "contact.go"
alias ContactVars = i32; //enums:enum
const  ContactA: ContactVars = 0;
const  ContactB: ContactVars = 1;
const  ContactNormX: ContactVars = 2;
const  ContactNormY: ContactVars = 3;
const  ContactNormZ: ContactVars = 4;
const  ContactPointX: ContactVars = 5;
const  ContactPointY: ContactVars = 6;
const  ContactPointZ: ContactVars = 7;
const  ContactDist: ContactVars = 8;

//////// import: "control.go"
alias JointControlVars = i32; //enums:enum
const  JointControlForce: JointControlVars = 0;
const  JointTargetPos: JointControlVars    = 1;
const  JointTargetVel: JointControlVars = 2;
fn JointControl(idx: i32,dof: i32, vr: JointControlVars) -> f32 {
	return JointControls[Index2D(TensorStrides[60], TensorStrides[61], u32(JointDoFIndex(idx, dof)), u32(vr))];
}

//////// import: "dynamics.go"
alias DynamicVars = i32; //enums:enum
const  DynIndex: DynamicVars = 0;
const  DynPosX: DynamicVars = 1;
const  DynPosY: DynamicVars = 2;
const  DynPosZ: DynamicVars = 3;
const  DynQuatX: DynamicVars = 4;
const  DynQuatY: DynamicVars = 5;
const  DynQuatZ: DynamicVars = 6;
const  DynQuatW: DynamicVars = 7;
const  DynVelX: DynamicVars = 8;
const  DynVelY: DynamicVars = 9;
const  DynVelZ: DynamicVars = 10;
const  DynAngVelX: DynamicVars = 11;
const  DynAngVelY: DynamicVars = 12;
const  DynAngVelZ: DynamicVars = 13;
const  DynAccX: DynamicVars = 14;
const  DynAccY: DynamicVars = 15;
const  DynAccZ: DynamicVars = 16;
const  DynAngAccX: DynamicVars = 17;
const  DynAngAccY: DynamicVars = 18;
const  DynAngAccZ: DynamicVars = 19;
const  DynForceX: DynamicVars = 20;
const  DynForceY: DynamicVars = 21;
const  DynForceZ: DynamicVars = 22;
const  DynTorqueX: DynamicVars = 23;
const  DynTorqueY: DynamicVars = 24;
const  DynTorqueZ: DynamicVars = 25;
const  DynDeltaX: DynamicVars = 26;
const  DynDeltaY: DynamicVars = 27;
const  DynDeltaZ: DynamicVars = 28;
const  DynAngDeltaX: DynamicVars = 29;
const  DynAngDeltaY: DynamicVars = 30;
const  DynAngDeltaZ: DynamicVars = 31;
fn DynamicIndex(idx: i32,cni: i32) -> i32 {
	return i32(bitcast<u32>(Dynamics[Index3D(TensorStrides[40], TensorStrides[41], TensorStrides[42], u32(idx), u32(cni), u32(DynIndex))]));
}
fn DynamicPos(idx: i32,cni: i32) -> vec3<f32> {
	return vec3<f32>(Dynamics[Index3D(TensorStrides[40], TensorStrides[41], TensorStrides[42], u32(idx), u32(cni), u32(DynPosX))], Dynamics[Index3D(TensorStrides[40], TensorStrides[41], TensorStrides[42], u32(idx), u32(cni), u32(DynPosY))], Dynamics[Index3D(TensorStrides[40], TensorStrides[41], TensorStrides[42], u32(idx), u32(cni), u32(DynPosZ))]);
}
fn DynamicQuat(idx: i32,cni: i32) -> vec4<f32> {
	return vec4<f32>(Dynamics[Index3D(TensorStrides[40], TensorStrides[41], TensorStrides[42], u32(idx), u32(cni), u32(DynQuatX))], Dynamics[Index3D(TensorStrides[40], TensorStrides[41], TensorStrides[42], u32(idx), u32(cni), u32(DynQuatY))], Dynamics[Index3D(TensorStrides[40], TensorStrides[41], TensorStrides[42], u32(idx), u32(cni), u32(DynQuatZ))], Dynamics[Index3D(TensorStrides[40], TensorStrides[41], TensorStrides[42], u32(idx), u32(cni), u32(DynQuatW))]);
}
fn DynamicDelta(idx: i32,cni: i32) -> vec3<f32> {
	return vec3<f32>(Dynamics[Index3D(TensorStrides[40], TensorStrides[41], TensorStrides[42], u32(idx), u32(cni), u32(DynDeltaX))], Dynamics[Index3D(TensorStrides[40], TensorStrides[41], TensorStrides[42], u32(idx), u32(cni), u32(DynDeltaY))], Dynamics[Index3D(TensorStrides[40], TensorStrides[41], TensorStrides[42], u32(idx), u32(cni), u32(DynDeltaZ))]);
}
fn DynamicAngDelta(idx: i32,cni: i32) -> vec3<f32> {
	return vec3<f32>(Dynamics[Index3D(TensorStrides[40], TensorStrides[41], TensorStrides[42], u32(idx), u32(cni), u32(DynAngDeltaX))], Dynamics[Index3D(TensorStrides[40], TensorStrides[41], TensorStrides[42], u32(idx), u32(cni), u32(DynAngDeltaY))], Dynamics[Index3D(TensorStrides[40], TensorStrides[41], TensorStrides[42], u32(idx), u32(cni), u32(DynAngDeltaZ))]);
}

//////// import: "enumgen.go"
const BodyVarsN: BodyVars = 37;
const ContactVarsN: ContactVars = 9;
const JointControlVarsN: JointControlVars = 3;
const DynamicVarsN: DynamicVars = 32;
const GPUVarsN: GPUVars = 8;
const JointTypesN: JointTypes = 7;
const JointVarsN: JointVars = 50;
const JointDoFVarsN: JointDoFVars = 7;
const ShapesN: Shapes = 4;

//////// import: "joint.go"
const JointLimitUnlimited = 1e10;
alias JointTypes = i32; //enums:enum
const  Prismatic: JointTypes = 0;
const  Revolute: JointTypes = 1;
const  Ball: JointTypes = 2;
const  Fixed: JointTypes = 3;
const  Free: JointTypes = 4;
const  Distance: JointTypes = 5;
const  D6: JointTypes = 6;
alias JointVars = i32; //enums:enum
const  JointType: JointVars = 0;
const  JointEnabled: JointVars = 1;
const  JointParent: JointVars = 2;
const  JointChild: JointVars = 3;
const  JointPPosX: JointVars = 4;
const  JointPPosY: JointVars = 5;
const  JointPPosZ: JointVars = 6;
const  JointPQuatX: JointVars = 7;
const  JointPQuatY: JointVars = 8;
const  JointPQuatZ: JointVars = 9;
const  JointPQuatW: JointVars = 10;
const  JointCPosX: JointVars = 11;
const  JointCPosY: JointVars = 12;
const  JointCPosZ: JointVars = 13;
const  JointCQuatX: JointVars = 14;
const  JointCQuatY: JointVars = 15;
const  JointCQuatZ: JointVars = 16;
const  JointCQuatW: JointVars = 17;
const  JointLinearDoFN: JointVars = 18;
const  JointAngularDoFN: JointVars = 19;
const  JointDoF1: JointVars = 20;
const  JointDoF2: JointVars = 21;
const  JointDoF3: JointVars = 22;
const  JointDoF4: JointVars = 23;
const  JointDoF5: JointVars = 24;
const  JointDoF6: JointVars = 25;
const  JointPForceX: JointVars = 26;
const  JointPForceY: JointVars = 27;
const  JointPForceZ: JointVars = 28;
const  JointPTorqueX: JointVars = 29;
const  JointPTorqueY: JointVars = 30;
const  JointPTorqueZ: JointVars = 31;
const  JointCForceX: JointVars = 32;
const  JointCForceY: JointVars = 33;
const  JointCForceZ: JointVars = 34;
const  JointCTorqueX: JointVars = 35;
const  JointCTorqueY: JointVars = 36;
const  JointCTorqueZ: JointVars = 37;
const  JointPDeltaX: JointVars = 38;
const  JointPDeltaY: JointVars = 39;
const  JointPDeltaZ: JointVars = 40;
const  JointPAngDeltaX: JointVars = 41;
const  JointPAngDeltaY: JointVars = 42;
const  JointPAngDeltaZ: JointVars = 43;
const  JointCDeltaX: JointVars = 44;
const  JointCDeltaY: JointVars = 45;
const  JointCDeltaZ: JointVars = 46;
const  JointCAngDeltaX: JointVars = 47;
const  JointCAngDeltaY: JointVars = 48;
const  JointCAngDeltaZ: JointVars = 49;
fn GetJointType(idx: i32) -> JointTypes {
	return JointTypes(bitcast<u32>(Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointType))]));
}
fn GetJointEnabled(idx: i32) -> bool {
	var je = bitcast<u32>(Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointEnabled))]);return je != 0;
}
fn JointParentIndex(idx: i32) -> i32 {
	return i32(bitcast<u32>(Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointParent))]));
}
fn JointChildIndex(idx: i32) -> i32 {
	return i32(bitcast<u32>(Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointChild))]));
}
fn GetJointLinearDoFN(idx: i32) -> i32 {
	return i32(bitcast<u32>(Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointLinearDoFN))]));
}
fn GetJointAngularDoFN(idx: i32) -> i32 {
	return i32(bitcast<u32>(Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointAngularDoFN))]));
}
fn JointDoFIndex(idx: i32,dof: i32) -> i32 {
	return i32(bitcast<u32>(Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(i32(JointDoF1) + dof))]));
}
fn JointPPos(idx: i32) -> vec3<f32> {
	return vec3<f32>(Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointPPosX))], Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointPPosY))], Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointPPosZ))]);
}
fn JointPQuat(idx: i32) -> vec4<f32> {
	return vec4<f32>(Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointPQuatX))], Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointPQuatY))], Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointPQuatZ))], Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointPQuatW))]);
}
fn JointCPos(idx: i32) -> vec3<f32> {
	return vec3<f32>(Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointCPosX))], Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointCPosY))], Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointCPosZ))]);
}
fn JointCQuat(idx: i32) -> vec4<f32> {
	return vec4<f32>(Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointCQuatX))], Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointCQuatY))], Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointCQuatZ))], Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointCQuatW))]);
}
fn SetJointPDelta(idx: i32, f: vec3<f32>) {
	Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointPDeltaX))] = f.x;
	Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointPDeltaY))] = f.y;
	Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointPDeltaZ))] = f.z;
}
fn SetJointPAngDelta(idx: i32, t: vec3<f32>) {
	Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointPAngDeltaX))] = t.x;
	Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointPAngDeltaY))] = t.y;
	Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointPAngDeltaZ))] = t.z;
}
fn SetJointCDelta(idx: i32, f: vec3<f32>) {
	Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointCDeltaX))] = f.x;
	Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointCDeltaY))] = f.y;
	Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointCDeltaZ))] = f.z;
}
fn SetJointCAngDelta(idx: i32, t: vec3<f32>) {
	Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointCAngDeltaX))] = t.x;
	Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointCAngDeltaY))] = t.y;
	Joints[Index2D(TensorStrides[10], TensorStrides[11], u32(idx), u32(JointCAngDeltaZ))] = t.z;
}
alias JointDoFVars = i32; //enums:enum
const  JointAxisX: JointDoFVars = 0;
const  JointAxisY: JointDoFVars = 1;
const  JointAxisZ: JointDoFVars = 2;
const  JointLimitLower: JointDoFVars = 3;
const  JointLimitUpper: JointDoFVars = 4;
const  JointStiff: JointDoFVars = 5;
const  JointDamp: JointDoFVars = 6;
fn JointAxisDoF(didx: i32) -> vec3<f32> {
	return vec3<f32>(JointDoFs[Index2D(TensorStrides[20], TensorStrides[21], u32(didx), u32(JointAxisX))], JointDoFs[Index2D(TensorStrides[20], TensorStrides[21], u32(didx), u32(JointAxisY))], JointDoFs[Index2D(TensorStrides[20], TensorStrides[21], u32(didx), u32(JointAxisZ))]);
}
fn JointAxis(idx: i32,dof: i32) -> vec3<f32> {
	return JointAxisDoF(JointDoFIndex(idx, dof));
}
fn JointDoF(idx: i32,dof: i32, vr: JointDoFVars) -> f32 {
	return JointDoFs[Index2D(TensorStrides[20], TensorStrides[21], u32(JointDoFIndex(idx, dof)), u32(vr))];
}

//////// import: "params.go"
struct PhysParams {
	Iterations: i32,
	Dt: f32,
	SoftRelax: f32,
	JointLinearRelax: f32,
	JointAngularRelax: f32,
	JointLinearComply: f32,
	JointAngularComply: f32,
	ContactRelax: f32,
	AngularDamping: f32,
	ContactWeighting: i32,
	Restitution: i32,
	DynamicsN: i32,
	JointsN: i32,
	JointDoFsN: i32,
	BodyJointsMax: i32,
	Cur: i32,
	Next: i32,
	pad: i32,
	pad1: i32,
	pad2: i32,
	Gravity: vec4<f32>,
}

//////// import: "shapes.go"
alias Shapes = i32; //enums:enum
const  Box: Shapes = 0;
const  Sphere: Shapes = 1;
const  Cylinder: Shapes = 2;
const  Capsule: Shapes = 3;

//////// import: "slmath-matrix3.go"

//////// import: "slmath-quaternion.go"
fn QuatLength(q: vec4<f32>) -> f32 {
	return sqrt(q.x*q.x + q.y*q.y + q.z*q.z + q.w*q.w);
}
fn QuatNormalize(q: vec4<f32>) -> vec4<f32> {
	var nq: vec4<f32>;
	var l = QuatLength(q);
	if (l == 0) {
		nq.x = f32(0);
		nq.y = f32(0);
		nq.z = f32(0);
		nq.w = f32(1);
	} else {
		l = 1 / l;
		nq.x *= l;
		nq.y *= l;
		nq.z *= l;
		nq.w *= l;
	}return nq;
}
fn MulQuatVector(q: vec4<f32>, v: vec3<f32>) -> vec3<f32> {
	var xyz = vec3<f32>(q.x, q.y, q.z);
	var t = MulScalar3(Cross3(xyz, v), f32(f32(2)));return v+(MulScalar3(t, q.w))+(Cross3(xyz, t));
}
fn MulQuatVectorInverse(q: vec4<f32>, v: vec3<f32>) -> vec3<f32> {
	var xyz = vec3<f32>(q.x, q.y, q.z);
	var t = MulScalar3(Cross3(xyz, v), f32(f32(2)));return v-(MulScalar3(t, q.w))+(Cross3(xyz, t));
}
fn MulQuats(a: vec4<f32>,b: vec4<f32>) -> vec4<f32> {
	var q: vec4<f32>;
	q.x = a.x*b.w + a.w*b.x + a.y*b.z - a.z*b.y;
	q.y = a.y*b.w + a.w*b.y + a.z*b.x - a.x*b.z;
	q.z = a.z*b.w + a.w*b.z + a.x*b.y - a.y*b.x;
	q.w = a.w*b.w - a.x*b.x - a.y*b.y - a.z*b.z;return q;
}
fn MulSpatialTransforms(aP: vec3<f32>, aQ: vec4<f32>, bP: vec3<f32>, bQ: vec4<f32>, oP: ptr<function,vec3<f32>>, oQ: ptr<function,vec4<f32>>) {
	*oP = MulQuatVector(aQ, bP)+(aP);
	*oQ = MulQuats(aQ, bQ);
}
fn MulSpatialPoint(xP: vec3<f32>, xQ: vec4<f32>, p: vec3<f32>) -> vec3<f32> {
	var dp = MulQuatVector(xQ, p);return dp+(xP);
}
fn SpatialTransformInverse(p: vec3<f32>, q: vec4<f32>, oP: ptr<function,vec3<f32>>, oQ: ptr<function,vec4<f32>>) {
	var qi = QuatInverse(q);
	*oP = Negate3(MulQuatVector(qi, p));
	*oQ = qi;
}
fn QuatInverse(q: vec4<f32>) -> vec4<f32> {
	var nq = q;
	nq.x *= f32(-1);
	nq.y *= f32(-1);
	nq.z *= f32(-1);return QuatNormalize(nq);
}
fn QuatDot(q: vec4<f32>,o: vec4<f32>) -> f32 {
	return q.x*o.x + q.y*o.y + q.z*o.z + q.w*o.w;
}
fn QuatMulScalar(q: vec4<f32>, s: f32) -> vec4<f32> {
	var nq = q;
	nq.x *= s;
	nq.y *= s;
	nq.z *= s;
	nq.w *= s;return nq;
}

//////// import: "slmath-vector3.go"
fn MulScalar3(v: vec3<f32>, s: f32) -> vec3<f32> {
	return vec3<f32>(v.x*s, v.y*s, v.z*s);
}
fn DivScalar3(v: vec3<f32>, s: f32) -> vec3<f32> {
	return vec3<f32>(v.x/s, v.y/s, v.z/s);
}
fn DivSafe3(v: vec3<f32>, o: vec3<f32>) -> vec3<f32> {
	var nv = v;
	if (o.x != 0) {
		nv.x /= o.x;
	}
	if (o.y != 0) {
		nv.y /= o.y;
	}
	if (o.z != 0) {
		nv.z /= o.z;
	}return nv;
}
fn Negate3(v: vec3<f32>) -> vec3<f32> {
	return vec3<f32>(-v.x, -v.y, -v.z);
}
fn Length3(v: vec3<f32>) -> f32 {
	return sqrt(v.x*v.x + v.y*v.y + v.z*v.z);
}
fn LengthSquared3(v: vec3<f32>) -> f32 {
	return v.x*v.x + v.y*v.y + v.z*v.z;
}
fn Dot3(v: vec3<f32>,o: vec3<f32>) -> f32 {
	return v.x*o.x + v.y*o.y + v.z*o.z;
}
fn Max3(v: vec3<f32>,o: vec3<f32>) -> vec3<f32> {
	return vec3<f32>(max(v.x, o.x), max(v.y, o.y), max(v.z, o.z));
}
fn Min3(v: vec3<f32>,o: vec3<f32>) -> vec3<f32> {
	return vec3<f32>(min(v.x, o.x), min(v.y, o.y), min(v.z, o.z));
}
fn Abs3(v: vec3<f32>) -> vec3<f32> {
	return vec3<f32>(abs(v.x), abs(v.y), abs(v.z));
}
fn Normal3(v: vec3<f32>) -> vec3<f32> {
	return DivScalar3(v, Length3(v));
}
fn Cross3(v: vec3<f32>,o: vec3<f32>) -> vec3<f32> {
	return vec3<f32>(v.y*o.z-v.z*o.y, v.z*o.x-v.x*o.z, v.x*o.y-v.y*o.x);
}
fn Dim3(v: vec3<f32>, dim: i32) -> f32 {
	if (dim == 0) {
		return v.x;
	}
	if (dim == 1) {
		return v.y;
	}return v.z;
}
fn SetDim3(v: vec3<f32>, dim: i32, val: f32) -> vec3<f32> {
	var nv = v;
	if (dim == 0) {
		nv.x = val;
	}
	if (dim == 1) {
		nv.y = val;
	}
	if (dim == 3) {
		nv.z = val;
	}return nv;
}

//////// import: "step.go"

//////// import: "step_body.go"

//////// import: "step_joint.go"
fn StepSolveJoints(i: u32) { //gosl:kernel
	let params = Params[0];
	var ji = i32(i);
	if (ji >= params.JointsN) {
		return;
	}
	var jt = GetJointType(ji);
	if (jt == Free || !GetJointEnabled(ji)) {
		return;
	}
	var jPi = JointParentIndex(ji);
	var jPbi = i32(-1);
	if (jPi >= 0) {
		jPbi = DynamicIndex(jPi, params.Cur);
	}
	var jCi = JointChildIndex(ji);
	var jCbi = DynamicIndex(jCi, params.Cur);
	var jLinearN = GetJointLinearDoFN(ji);
	var jAngularN = GetJointAngularDoFN(ji);
	var jPR = JointPPos(ji);
	var jPQ = JointPQuat(ji);
	var xwPR = jPR; // world xform, parent, pos
	var xwPQ = jPQ; // quat
	var mInvP = f32(0.0);
	var iInvP = mat3x3f(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0);
	var posePR = jPR;
	var posePQ = jPQ;
	var comP: vec3<f32>;
	var
	vP: vec3<f32>;
	var wP: vec3<f32>;
	if (jPi >= 0) {
		posePR = DynamicPos(jPi, params.Next); // now using next
		posePQ = DynamicQuat(jPi, params.Next);
		MulSpatialTransforms(posePR, posePQ, jPR, jPQ, &xwPR, &xwPQ);
		comP = BodyCom(jPbi);
		mInvP = Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(jPbi), u32(BodyInvMass))];
		iInvP = BodyInvInertia(jPbi);
		vP = DynamicDelta(jPi, params.Next);
		wP = DynamicAngDelta(jPi, params.Next);
	}
	var poseCR = DynamicPos(jCi, params.Next);
	var poseCQ = DynamicQuat(jCi, params.Next);
	var jCR = JointCPos(ji);
	var jCQ = JointCQuat(ji);
	var xwCR = jCR;
	var xwCQ = jCQ;
	MulSpatialTransforms(poseCR, poseCQ, jCR, jCQ, &xwCR, &xwCQ);
	var comC = BodyCom(jCbi);
	var mInvC = Bodies[Index2D(TensorStrides[0], TensorStrides[1], u32(jCbi), u32(BodyInvMass))];
	var iInvC = BodyInvInertia(jCbi);
	var vC = DynamicDelta(jCi, params.Next);
	var wC = DynamicAngDelta(jCi, params.Next);
	if (mInvP == 0.0 && mInvC == 0.0) { // connection between two immovable bodies
		return;
	}
	var linDeltaP: vec3<f32>;
	var angDeltaP: vec3<f32>;
	var linDeltaC: vec3<f32>;
	var angDeltaC: vec3<f32>;
	var relPoseR = xwPR;
	var relPoseQ = xwPQ;
	SpatialTransformInverse(xwPR, xwPQ, &relPoseR, &relPoseQ);
	MulSpatialTransforms(relPoseR, relPoseQ, xwCR, xwCQ, &relPoseR, &relPoseQ);
	var wComP = MulSpatialPoint(posePR, posePQ, comP);
	var wComC = MulSpatialPoint(poseCR, poseCQ, comC);
	if (jt == Distance) {
		var dP = xwPR-(wComP);
		var dC = xwCR-(wComC);
		var lo = JointDoF(ji, i32(i32(0)), JointLimitLower); // only first one has constraint
		var up = JointDoF(ji, i32(i32(0)), JointLimitUpper);
		if (lo < 0 && up < 0) { // not limited
			return;
		}
		var d = Length3(relPoseR);
		var err = f32(0.0);
		if (lo >= 0.0 && d < lo) {
			err = d - lo;
			relPoseR = Normal3(wComC-(wComP))*(err);
		} else if (up >= 0.0 && d > up) {
			err = d - up;
		}
		if (abs(err) > 1e-9) {
			var linearC = relPoseR;
			var linearP = Negate3(linearC);
			dC = xwCR-(wComC);
			var angularP = Negate3(Cross3(dP, linearC));
			var angularC = Cross3(dC, linearC);
			var derr = Dot3(linearP, vP) + Dot3(linearC, vC) + Dot3(angularP, wP) + Dot3(angularC, wC);
			var lambdaIn = f32(0.0);
			var compliance = params.JointLinearComply;
			var ke = JointDoF(ji, i32(i32(0)), JointStiff);
			var kd = JointDoF(ji, i32(i32(0)), JointDamp);
			if (ke > 0.0) {
				compliance = 1.0 / ke;
			}
			var dLambda = PositionalCorrection(err, derr, posePQ, poseCQ, mInvP, mInvC,
				iInvP, iInvC, linearP, linearC, angularP, angularC, lambdaIn, compliance, kd, params.Dt);
			linDeltaP = linDeltaP+(linearP*(dLambda * params.JointLinearRelax));
			angDeltaP = angDeltaP+(angularP*(dLambda * params.JointAngularRelax));
			linDeltaC = linDeltaC+(linearC*(dLambda * params.JointLinearRelax));
			angDeltaC = angDeltaC+(angularC*(dLambda * params.JointAngularRelax));
		}
	} else { // compute joint target, stiffness, damping
		var axisLimitsD: vec3<f32>;
		var axisLimitsA: vec3<f32>;
		var axisTargetPosKeD: vec3<f32>;
		var axisTargetPosKeA: vec3<f32>;
		var axisTargetVelKdD: vec3<f32>;
		var axisTargetVelKdA: vec3<f32>;
		for (var dof=0; dof<jLinearN; dof++) {
			var axis = JointAxis(ji, dof);
			JointAxisLimitsUpdate(dof, axis, JointDoF(ji, dof, JointLimitLower), JointDoF(ji, dof, JointLimitUpper), &axisLimitsD, &axisLimitsA);
			var ke = JointDoF(ji, dof, JointStiff);
			var kd = JointDoF(ji, dof, JointDamp);
			var targetPos = JointControl(ji, dof, JointTargetPos);
			var targetVel = JointControl(ji, dof, JointTargetVel);
			if (ke > 0.0) { // has position control
				JointAxisTarget(axis, targetPos, ke, &axisTargetPosKeD, &axisTargetPosKeA);
			}
			if (kd > 0.0) { // has velocity control
				JointAxisTarget(axis, targetVel, kd, &axisTargetVelKdD, &axisTargetVelKdA);
			}
		}
		var axisStiffness = axisTargetPosKeA;
		var axisDamping = axisTargetVelKdA;
		axisTargetPosKeD = DivSafe3(axisTargetPosKeD, axisStiffness);
		axisTargetVelKdD = DivSafe3(axisTargetVelKdD, axisDamping);
		var axisLimitsLower = axisLimitsD;
		var axisLimitsUpper = axisLimitsA;
		var dP = xwCR-(wComP);
		var dC = xwCR-(MulSpatialPoint(poseCR, poseCQ, comC));
		for (var dim=0; dim<i32(3); dim++) {
			var e = Dim3(relPoseR, dim);
			var dima = SetDim3(vec3<f32>(0, 0, 0), dim, f32(f32(1))); // axis for dim
			var linearC = MulQuatVector(xwPQ, dima);
			var linearP = Negate3(linearC);
			var angularP = Negate3(Cross3(dP, linearC));
			var angularC = Cross3(dC, linearC);
			var derr = Dot3(linearP, vP) + Dot3(linearC, vC) + Dot3(angularP, wP) + Dot3(angularC, wC);
			var err = f32(0.0);
			var compliance = params.JointLinearComply;
			var damping = f32(0.0);
			var targetVel = Dim3(axisTargetVelKdD, dim);
			var derrRel = derr - targetVel;
			var lower = Dim3(axisLimitsLower, dim);
			var upper = Dim3(axisLimitsUpper, dim);
			if (e < lower) {
				err = e - lower;
			} else if (e > upper) {
				err = e - upper;
			} else {
				var targetPos = Dim3(axisTargetPosKeD, dim);
				targetPos = clamp(targetPos, lower, upper);
				var ke = Dim3(axisStiffness, dim);
				var kd = Dim3(axisDamping, dim);
				if (ke > 0.0) {
					err = e - targetPos;
					compliance = 1.0 / ke;
					damping = Dim3(axisDamping, dim);
				} else if (kd > 0.0) {
					compliance = 1.0 / kd;
					damping = kd;
				}
			}
			if (abs(err) > 1e-9 || abs(derrRel) > 1e-9) {
				var lambdaIn = f32(0.0);
				var dLambda = PositionalCorrection(err, derrRel, posePQ, poseCQ, mInvP, mInvC,
					iInvP, iInvC, linearP, linearC, angularP, angularC, lambdaIn, compliance, damping, params.Dt);
				linDeltaP = linDeltaP+(linearP*(dLambda * params.JointLinearRelax));
				angDeltaP = angDeltaP+(angularP*(dLambda * params.JointAngularRelax));
				linDeltaC = linDeltaC+(linearC*(dLambda * params.JointLinearRelax));
				angDeltaC = angDeltaC+(angularC*(dLambda * params.JointAngularRelax));
			}
		}
	}
	if (jt == Fixed || jt == Prismatic || jt == Revolute || jt == D6) { // angular
		var qP = xwPQ;
		var qC = xwCQ;
		if (QuatDot(qP, qC) < 0) {
			qC = QuatMulScalar(qC, -1.0);
		}
		var relQ = MulQuats(QuatInverse(qP), qC);
		var qtwist = QuatNormalize(vec4<f32>(relQ.x, 0.0, 0.0, relQ.w));
		var qswing = MulQuats(relQ, QuatInverse(qtwist));
		var s = sqrt(relQ.x*relQ.x + relQ.w*relQ.w);
		var invs = 1.0 / s;
		var invscube = invs * invs * invs;
		var err0 = 2.0 * asin(clamp(qtwist.x, -1.0, 1.0));
		var err1 = qswing.y;
		var err2 = qswing.z;
		var grad0 = vec4<f32>(invs-relQ.x*relQ.x*invscube, 0.0, 0.0, -(relQ.w*relQ.x)*invscube);
		var grad1 = vec4<f32>(
			-relQ.w*(relQ.w*relQ.z+relQ.x*relQ.y)*invscube,
			relQ.w*invs,
			-relQ.x*invs,
			relQ.x*(relQ.w*relQ.z+relQ.x*relQ.y)*invscube);
		var grad2 = vec4<f32>(
			relQ.w*(relQ.w*relQ.y-relQ.x*relQ.z)*invscube,
			relQ.x*invs,
			relQ.w*invs,
			relQ.x*(relQ.z*relQ.x-relQ.w*relQ.y)*invscube);
		grad0 = QuatMulScalar(grad0, 2.0/abs(qtwist.w));
		var swing_sq = qswing.w * qswing.w;
		var angularEps = f32(1.0e-4);
		if (swing_sq+angularEps < 1.0) {
			var d = sqrt(1.0 - qswing.w*qswing.w);
			var theta = 2.0 * acos(clamp(qswing.w, -1.0, 1.0));
			var scale = theta / d;
			err1 *= scale;
			err2 *= scale;
			grad1 = QuatMulScalar(grad1, scale);
			grad2 = QuatMulScalar(grad2, scale);
		}
		var errs = vec3<f32>(err0, err1, err2);
		var gradX = vec3<f32>(grad0.x, grad1.x, grad2.x);
		var gradY = vec3<f32>(grad0.y, grad1.y, grad2.y);
		var gradZ = vec3<f32>(grad0.z, grad1.z, grad2.z);
		var gradW = vec3<f32>(grad0.w, grad1.w, grad2.w);
		var axisLimitsD: vec3<f32>;
		var axisLimitsA: vec3<f32>;
		var axisTargetPosKeD: vec3<f32>;
		var axisTargetPosKeA: vec3<f32>;
		var axisTargetVelKdD: vec3<f32>;
		var axisTargetVelKdA: vec3<f32>;
		for (var dof=0; dof<jAngularN; dof++) {
			var di = dof + jLinearN;
			var axis = JointAxis(ji, di);
			JointAxisLimitsUpdate(dof, axis, JointDoF(ji, di, JointLimitLower), JointDoF(ji, di, JointLimitUpper), &axisLimitsD, &axisLimitsA);
			var ke = JointDoF(ji, di, JointStiff);
			var kd = JointDoF(ji, di, JointDamp);
			var targetPos = JointControl(ji, di, JointTargetPos);
			var targetVel = JointControl(ji, di, JointTargetVel);
			if (ke > 0.0) { // has position control
				JointAxisTarget(axis, targetPos, ke, &axisTargetPosKeD, &axisTargetPosKeA);
			}
			if (kd > 0.0) { // has velocity control
				JointAxisTarget(axis, targetVel, kd, &axisTargetVelKdD, &axisTargetVelKdA);
			}
		}
		var axisStiffness = axisTargetPosKeA;
		var axisDamping = axisTargetVelKdA;
		axisTargetPosKeD = DivSafe3(axisTargetPosKeD, axisStiffness);
		axisTargetVelKdD = DivSafe3(axisTargetVelKdD, axisDamping);
		var axisLimitsLower = axisLimitsD;
		var axisLimitsUpper = axisLimitsA;
		for (var dim=0; dim<i32(3); dim++) {
			var e = Dim3(errs, dim);
			var grad = vec4<f32>(Dim3(gradX, dim), Dim3(gradY, dim), Dim3(gradZ, dim), Dim3(gradW, dim));
			var quatC = MulQuats(MulQuats(QuatMulScalar(qP, f32(0.5)), grad), QuatInverse(qC));
			var angularC = vec3<f32>(quatC.x, quatC.y, quatC.z);
			var angularP = Negate3(angularC);
			var derr = Dot3(angularP, wP) + Dot3(angularC, wC);
			var err = f32(0.0);
			var compliance = params.JointLinearComply;
			var damping = f32(0.0);
			var targetVel = Dim3(axisTargetVelKdD, dim);
			var derrRel = derr - targetVel;
			var lower = Dim3(axisLimitsLower, dim);
			var upper = Dim3(axisLimitsUpper, dim);
			if (e < lower) {
				err = e - lower;
			} else if (e > upper) {
				err = e - upper;
			} else {
				var targetPos = Dim3(axisTargetPosKeD, dim);
				targetPos = clamp(targetPos, lower, upper);
				var ke = Dim3(axisStiffness, dim);
				var kd = Dim3(axisDamping, dim);
				if (ke > 0.0) {
					err = e - targetPos;
					compliance = 1.0 / ke;
					damping = Dim3(axisDamping, dim);
				} else if (kd > 0.0) {
					compliance = 1.0 / kd;
					damping = kd;
				}
			}
			var lambdaIn = f32(0);
			var dLambda = AngularCorrection(err, derrRel, posePQ, poseCQ, iInvP, iInvC, angularP, angularC, lambdaIn, compliance, damping, params.Dt);
			angDeltaP = angDeltaP+(angularP*(dLambda));
			angDeltaC = angDeltaC+(angularC*(dLambda));
		}
	}
	SetJointPDelta(ji, linDeltaP);
	SetJointPAngDelta(ji, angDeltaP);
	SetJointCDelta(ji, linDeltaC);
	SetJointCAngDelta(ji, angDeltaC);
}
fn JointAxisTarget(axis: vec3<f32>, targ: f32,weight: f32, axisTargets: ptr<function,vec3<f32>>,axisWeights: ptr<function,vec3<f32>>) {
	var weightedAxis = axis*(weight);
	*axisTargets = (*axisTargets)+(weightedAxis*(targ)); // weighted target (to be normalized later by sum of weights)
	*axisWeights = (*axisWeights)+(Abs3(weightedAxis));
}
fn PositionalCorrection(err: f32,derr: f32, tfaQ: vec4<f32>,tfbQ: vec4<f32>, mInva: f32,mInvb: f32, iInva: mat3x3f,iInvb: mat3x3f, lineara: vec3<f32>,linearb: vec3<f32>,angulara: vec3<f32>,angularb: vec3<f32>, lambdaIn: f32,compliance: f32,damping: f32,dt: f32) -> f32 {
	var denom = f32(0.0);
	denom += LengthSquared3(lineara) * mInva;
	denom += LengthSquared3(linearb) * mInvb;
	var rotAngulara = MulQuatVectorInverse(tfaQ, angulara);
	var rotAngularb = MulQuatVectorInverse(tfbQ, angularb);
	denom += Dot3(rotAngulara, iInva*(rotAngulara));
	denom += Dot3(rotAngularb, iInvb*(rotAngularb));
	var alpha = compliance;
	var gamma = compliance * damping;
	var deltaLambda = -(err + alpha*lambdaIn + gamma*derr);
	if (denom+alpha > 0.0) {
		deltaLambda /= (dt+gamma)*denom + alpha/dt;
	}return deltaLambda;
}
fn AngularCorrection(err: f32,derr: f32, tfaQ: vec4<f32>,tfbQ: vec4<f32>, iInva: mat3x3f,iInvb: mat3x3f, angulara: vec3<f32>,angularb: vec3<f32>, lambdaIn: f32,compliance: f32,damping: f32,dt: f32) -> f32 {
	var rotAngulara = MulQuatVectorInverse(tfaQ, angulara);
	var rotAngularb = MulQuatVectorInverse(tfbQ, angularb);
	var denom = f32(0.0);
	denom += Dot3(rotAngulara, iInva*(rotAngulara));
	denom += Dot3(rotAngularb, iInvb*(rotAngularb));
	var alpha = compliance;
	var gamma = compliance * damping;
	var deltaLambda = -(err + alpha*lambdaIn + gamma*derr);
	if (denom+alpha > 0.0) {
		deltaLambda /= (dt+gamma)*denom + alpha/dt;
	}return deltaLambda;
}
fn JointAxisLimitsUpdate(dof: i32, axis: vec3<f32>, lower: f32,upper: f32, axisLimitsD: ptr<function,vec3<f32>>,axisLimitsA: ptr<function,vec3<f32>>) {
	var loTemp = axis*(lower);
	var upTemp = axis*(upper);
	var lo = Min3(loTemp, upTemp);
	var up = Max3(loTemp, upTemp);
	if (dof == 0) {
		*axisLimitsD = lo;
		*axisLimitsA = up;
	} else {
		*axisLimitsD = Min3(*axisLimitsD, lo);
		*axisLimitsA = Max3(*axisLimitsD, up);
	}
}