// Code generated by 'yaegi extract cogentcore.org/lab/stats/histogram'. DO NOT EDIT.

package tensorsymbols

import (
	"cogentcore.org/lab/stats/histogram"
	"reflect"
)

func init() {
	Symbols["cogentcore.org/lab/stats/histogram/histogram"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"F64":      reflect.ValueOf(histogram.F64),
		"F64Table": reflect.ValueOf(histogram.F64Table),
	}
}
