// Code generated by "core generate -add-types"; DO NOT EDIT.

package main

import (
	"cogentcore.org/core/types"
)

var _ = types.AddType(&types.Type{Name: "main.Pendula", IDName: "pendula", Doc: "Pendula has sim params", Fields: []types.Field{{Name: "NPendula", Doc: "Number of bar elements to add to the pendulum. More interesting the more you add!"}, {Name: "StartVert", Doc: "StartVert starts the pendulum in the vertical orientation\n(else horizontal, so it has somewhere to go). Need to add force if vertical."}, {Name: "TargetDegFromVert", Doc: "TargetDegFromVert is the target number of degrees off of vertical\nfor each joint. Critical for this to not be 0 for StartVert."}, {Name: "ForceOn", Doc: "Timestep in msec to add a force"}, {Name: "ForceOff", Doc: "Timestep in msec to stop adding force"}, {Name: "Force", Doc: "Force to add"}, {Name: "HSize", Doc: "half-size of the pendulum elements."}, {Name: "Mass", Doc: "Mass of each bar (kg)"}, {Name: "Collide", Doc: "do the elements collide with each other?  this is currently bad!"}, {Name: "Stiff", Doc: "Stiff is the strength of the positional constraint to keep\neach bar in a vertical position."}, {Name: "Damp", Doc: "Damp is the strength of the velocity constraint to keep each\nbar not moving."}}})
