// Code generated by "gosl"; DO NOT EDIT

package slmathtest

import (
	"embed"
	"fmt"
	"math"
	"unsafe"
	"cogentcore.org/core/gpu"
	"cogentcore.org/lab/tensor"
)

//go:embed shaders/*.wgsl
var shaders embed.FS

var (
	// GPUInitialized is true once the GPU system has been initialized.
	// Prevents multiple initializations.
	GPUInitialized bool
	
	// ComputeGPU is the compute gpu device.
	// Set this prior to calling GPUInit() to use an existing device.
	ComputeGPU *gpu.GPU

	// BorrowedGPU is true if our ComputeGPU is set externally,
	// versus created specifically for this system. If external,
	// we don't release it.
	BorrowedGPU bool
	
	// UseGPU indicates whether to use GPU vs. CPU.
	UseGPU bool
)
// GPUSystem is a GPU compute System with kernels operating on the
// same set of data variables.
var GPUSystem *gpu.ComputeSystem

// GPUVars is an enum for GPU variables, for specifying what to sync.
type GPUVars int32 //enums:enum

const (
	ParamsVar GPUVars = 0
	DataVar GPUVars = 1
)

// Dummy tensor stride variable to avoid import error
var __TensorStrides tensor.Uint32

// GPUInit initializes the GPU compute system,
// configuring system(s), variables and kernels.
// It is safe to call multiple times: detects if already run.
func GPUInit() {
	if GPUInitialized {
		return
	}
	GPUInitialized = true
	if ComputeGPU == nil { // set prior to this call to use an external
		ComputeGPU = gpu.NewComputeGPU()
	} else {
		BorrowedGPU = true
	}
	gp := ComputeGPU
	
	_ = fmt.Sprintf("%g",math.NaN()) // keep imports happy
	{
		sy := gpu.NewComputeSystem(gp, "Default")
		GPUSystem = sy
		vars := sy.Vars()
		{
			sgp := vars.AddGroup(gpu.Storage, "Group_0")
			var vr *gpu.Var
			_ = vr
			vr = sgp.AddStruct("Params", int(unsafe.Sizeof(Values{})), 1, gpu.ComputeShader)
			vr.ReadOnly = true
			vr = sgp.AddStruct("Data", int(unsafe.Sizeof(Values{})), 1, gpu.ComputeShader)
			sgp.SetNValues(1)
		}
		var pl *gpu.ComputePipeline
		pl = gpu.NewComputePipelineShaderFS(shaders, "shaders/SLMathTest.wgsl", sy)
		pl.AddVarUsed(0, "Data")
		pl.AddVarUsed(0, "Params")
		sy.Config()
	}
}

// GPURelease releases the GPU compute system resources.
// Call this at program exit.
func GPURelease() {
	if GPUSystem != nil {
		GPUSystem.Release()
		GPUSystem = nil
	}

	if !BorrowedGPU && ComputeGPU != nil {
		ComputeGPU.Release()
	
	}
	ComputeGPU = nil
}

// RunSLMathTest runs the SLMathTest kernel with given number of elements,
// on either the CPU or GPU depending on the UseGPU variable.
// Can call multiple Run* kernels in a row, which are then all launched
// in the same command submission on the GPU, which is by far the most efficient.
// MUST call RunDone (with optional vars to sync) after all Run calls.
// Alternatively, a single-shot RunOneSLMathTest call does Run and Done for a
// single run-and-sync case.
func RunSLMathTest(n int) {
	if UseGPU {
		RunSLMathTestGPU(n)
	} else {
		RunSLMathTestCPU(n)
	}
}

// RunSLMathTestGPU runs the SLMathTest kernel on the GPU. See [RunSLMathTest] for more info.
func RunSLMathTestGPU(n int) {
	sy := GPUSystem
	pl := sy.ComputePipelines["SLMathTest"]
	ce, _ := sy.BeginComputePass()
	pl.Dispatch1D(ce, n, 64)
}

// RunSLMathTestCPU runs the SLMathTest kernel on the CPU.
func RunSLMathTestCPU(n int) {
	gpu.VectorizeFunc(0, n, SLMathTest)
}

// RunOneSLMathTest runs the SLMathTest kernel with given number of elements,
// on either the CPU or GPU depending on the UseGPU variable.
// This version then calls RunDone with the given variables to sync
// after the Run, for a single-shot Run-and-Done call. If multiple kernels
// can be run in sequence, it is much more efficient to do multiple Run*
// calls followed by a RunDone call.
func RunOneSLMathTest(n int, syncVars ...GPUVars) {
	if UseGPU {
		RunSLMathTestGPU(n)
		RunDone(syncVars...)
	} else {
		RunSLMathTestCPU(n)
	}
}
// RunDone must be called after Run* calls to start compute kernels.
// This actually submits the kernel jobs to the GPU, and adds commands
// to synchronize the given variables back from the GPU to the CPU.
// After this function completes, the GPU results will be available in 
// the specified variables.
func RunDone(syncVars ...GPUVars) {
	if !UseGPU {
		return
	}
	sy := GPUSystem
	sy.ComputeEncoder.End()
	ReadFromGPU(syncVars...)
	sy.EndComputePass()
	SyncFromGPU(syncVars...)
}

// ToGPU copies given variables to the GPU for the system.
func ToGPU(vars ...GPUVars) {
	if !UseGPU {
		return
	}
	sy := GPUSystem
	syVars := sy.Vars()
	for _, vr := range vars {
		switch vr {
		case ParamsVar:
			v, _ := syVars.ValueByIndex(0, "Params", 0)
			gpu.SetValueFrom(v, Params)
		case DataVar:
			v, _ := syVars.ValueByIndex(0, "Data", 0)
			gpu.SetValueFrom(v, Data)
		}
	}
}
// RunGPUSync can be called to synchronize data between CPU and GPU.
// Any prior ToGPU* calls will execute to send data to the GPU,
// and any subsequent RunDone* calls will copy data back from the GPU.
func RunGPUSync() {
	if !UseGPU {
		return
	}
	sy := GPUSystem
	sy.BeginComputePass()
}

// ReadFromGPU starts the process of copying vars to the GPU.
func ReadFromGPU(vars ...GPUVars) {
	sy := GPUSystem
	syVars := sy.Vars()
	for _, vr := range vars {
		switch vr {
		case ParamsVar:
			v, _ := syVars.ValueByIndex(0, "Params", 0)
			v.GPUToRead(sy.CommandEncoder)
		case DataVar:
			v, _ := syVars.ValueByIndex(0, "Data", 0)
			v.GPUToRead(sy.CommandEncoder)
		}
	}
}

// SyncFromGPU synchronizes vars from the GPU to the actual variable.
func SyncFromGPU(vars ...GPUVars) {
	sy := GPUSystem
	syVars := sy.Vars()
	for _, vr := range vars {
		switch vr {
		case ParamsVar:
			v, _ := syVars.ValueByIndex(0, "Params", 0)
			v.ReadSync()
			gpu.ReadToBytes(v, Params)
		case DataVar:
			v, _ := syVars.ValueByIndex(0, "Data", 0)
			v.ReadSync()
			gpu.ReadToBytes(v, Data)
		}
	}
}

// GetParams returns a pointer to the given global variable: 
// [Params] []Values at given index. This directly processed in the GPU code,
// so this function call is an equivalent for the CPU.
func GetParams(idx uint32) *Values {
	return &Params[idx]
}

// GetData returns a pointer to the given global variable: 
// [Data] []Values at given index. This directly processed in the GPU code,
// so this function call is an equivalent for the CPU.
func GetData(idx uint32) *Values {
	return &Data[idx]
}
