// Code generated by "goal build"; DO NOT EDIT.
//line control.goal:1
// Copyright (c) 2025, Cogent Core. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package physics

import "cogentcore.org/core/math32"

//gosl:start

// JointControlVars are external joint control input variables stored in tensor.Float32.
// These must be in one-to-one correspondence with the joints.
type JointControlVars int32 //enums:enum

const (
	// Joint force and torque inputs
	JointCtrlForceX JointControlVars = iota
	JointCtrlForceY
	JointCtrlForceZ
	JointCtrlTorqueX
	JointCtrlTorqueY
	JointCtrlTorqueZ

	// target values (1 DoF use JointTargetPosX)
	JointTargetPosX
	JointTargetPosY
	JointTargetPosZ

	JointTargetRotX
	JointTargetRotY
	JointTargetRotZ
	JointTargetRotW

	// target velocity
	JointTargetVelX
	JointTargetVelY
	JointTargetVelZ

	// target angular velocity
	JointTargetAngVelX
	JointTargetAngVelY
	JointTargetAngVelZ
)

func JointControlForce(idx int32) math32.Vector3 {
	return math32.Vec3(JointControls.Value(int(idx), int(JointCtrlForceX)), JointControls.Value(int(idx), int(JointCtrlForceY)), JointControls.Value(int(idx), int(JointCtrlForceZ)))
}

func SetJointControlForce(idx int32, f math32.Vector3) {
	JointControls.Set(f.X, int(idx), int(JointCtrlForceX))
	JointControls.Set(f.Y, int(idx), int(JointCtrlForceY))
	JointControls.Set(f.Z, int(idx), int(JointCtrlForceZ))
}

func JointControlTorque(idx int32) math32.Vector3 {
	return math32.Vec3(JointControls.Value(int(idx), int(JointCtrlTorqueX)), JointControls.Value(int(idx), int(JointCtrlTorqueY)), JointControls.Value(int(idx), int(JointCtrlTorqueZ)))
}

func SetJointControlTorque(idx int32, f math32.Vector3) {
	JointControls.Set(f.X, int(idx), int(JointCtrlTorqueX))
	JointControls.Set(f.Y, int(idx), int(JointCtrlTorqueY))
	JointControls.Set(f.Z, int(idx), int(JointCtrlTorqueZ))
}

func JointTargetPos(idx int32) math32.Vector3 {
	return math32.Vec3(JointControls.Value(int(idx), int(JointTargetPosX)), JointControls.Value(int(idx), int(JointTargetPosY)), JointControls.Value(int(idx), int(JointTargetPosZ)))
}

func SetJointTargetPos(idx int32, f math32.Vector3) {
	JointControls.Set(f.X, int(idx), int(JointTargetPosX))
	JointControls.Set(f.Y, int(idx), int(JointTargetPosY))
	JointControls.Set(f.Z, int(idx), int(JointTargetPosZ))
}

func JointTargetRot(idx int32) math32.Vector3 {
	return math32.Vec3(JointControls.Value(int(idx), int(JointTargetRotX)), JointControls.Value(int(idx), int(JointTargetRotY)), JointControls.Value(int(idx), int(JointTargetRotZ)))
}

func SetJointTargetRot(idx int32, f math32.Vector3) {
	JointControls.Set(f.X, int(idx), int(JointTargetRotX))
	JointControls.Set(f.Y, int(idx), int(JointTargetRotY))
	JointControls.Set(f.Z, int(idx), int(JointTargetRotZ))
}

func JointTargetVel(idx int32) math32.Vector3 {
	return math32.Vec3(JointControls.Value(int(idx), int(JointTargetVelX)), JointControls.Value(int(idx), int(JointTargetVelY)), JointControls.Value(int(idx), int(JointTargetVelZ)))
}

func SetJointTargetVel(idx int32, f math32.Vector3) {
	JointControls.Set(f.X, int(idx), int(JointTargetVelX))
	JointControls.Set(f.Y, int(idx), int(JointTargetVelY))
	JointControls.Set(f.Z, int(idx), int(JointTargetVelZ))
}

func JointTargetAngVel(idx int32) math32.Vector3 {
	return math32.Vec3(JointControls.Value(int(idx), int(JointTargetAngVelX)), JointControls.Value(int(idx), int(JointTargetAngVelY)), JointControls.Value(int(idx), int(JointTargetAngVelZ)))
}

func SetJointTargetAngVel(idx int32, f math32.Vector3) {
	JointControls.Set(f.X, int(idx), int(JointTargetAngVelX))
	JointControls.Set(f.Y, int(idx), int(JointTargetAngVelY))
	JointControls.Set(f.Z, int(idx), int(JointTargetAngVelZ))
}

//gosl:end
