// Code generated by "goal build"; DO NOT EDIT.
//line server.goal:1
// Copyright (c) 2025, Cogent Lab. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package baremetal

// Server specifies a bare metal Server.
type Server struct {
	// Name is the alias used for gossh.
	Name string

	// SSH is string to gossh to.
	SSH string

	// NGPUs is the number of GPUs on this server.
	NGPUs int

	// Used is the number of GPUs current being used.
	Used int `edit:"-" toml:"-"`
}

// OpenSSH opens the SSH connection for this server.
func (sv *Server) OpenSSH() {
	goalrun.Run("gossh", sv.SSH, sv.Name)
}

// ID returns the server SSH ID string: @Name
func (sv *Server) ID() string {
	return "@" + sv.Name
}

// Use makes this the active server.
func (sv *Server) Use() {
	goalrun.Run(sv.ID())
}
