// Code generated by "core generate -add-types"; DO NOT EDIT.

package main

import (
	"cogentcore.org/core/types"
)

var _ = types.AddType(&types.Type{Name: "main.Collide", IDName: "collide", Doc: "Collide has sim params", Fields: []types.Field{{Name: "ShapeA", Doc: "Shape of left body"}, {Name: "ShapeB", Doc: "Shape of right body"}, {Name: "SizeA", Doc: "Size of left body (radius, capsule, cylinder, box are 2x taller)"}, {Name: "SizeB", Doc: "Size of right body (radius, capsule, cylinder, box are 2x taller)"}, {Name: "MassA", Doc: "Mass of left object: if lighter than B, it will bounce back more."}, {Name: "MassB", Doc: "Mass of right object: if lighter than B, it will move faster."}, {Name: "ZposA", Doc: "Z (depth) position: offset to get different collision angles."}, {Name: "ZposB", Doc: "Z (depth) position: offset to get different collision angles."}, {Name: "PushMass", Doc: "Mass of the pusher panel: if lighter, it transfers less energy."}, {Name: "Friction", Doc: "Friction is for sliding: around 0.01 seems pretty realistic"}, {Name: "FrictionTortion"}, {Name: "FrictionRolling", Doc: "FrictionRolling is for rolling: around 0.01 seems pretty realistic"}}})
