// Code generated by "gosl"; DO NOT EDIT
// kernel: SLMathTest

// // Params are the read-only parameters for the computation. // 
@group(0) @binding(1)
var<storage, read> Params: array<Values>;
@group(0) @binding(2)
var<storage, read_write> Data: array<Values>;

alias GPUVars = i32;

@compute @workgroup_size(64, 1, 1)
fn main(@builtin(workgroup_id) wgid: vec3<u32>, @builtin(num_workgroups) nwg: vec3<u32>, @builtin(local_invocation_index) loci: u32) {
	let idx = loci + (wgid.x + wgid.y * nwg.x + wgid.z * nwg.x * nwg.y) * 64;
	SLMathTest(idx);
}


//////// import: "slmathtest.go"
struct Values {
	Val:  f32,
	pad:  f32,
	pad1: f32,
	pad2: f32,
}
fn Vector2Test(v: vec2<f32>,o: vec2<f32>, s: f32, d: i32) -> f32 {
	var r = Polar2(s, s);
	r = r+(DivSafe2(v, o));
	r = r+(Negate2(v));
	r = r+(Max2(v, o));
	r = r+(Min2(v, o));
	r = r+(Abs2(v));
	r = r+(Floor2(v));
	r = r+(Ceil2(v));
	r = r+(Round2(v));
	r = r+(Clamp2(v, o, o));
	r = r+(ClampMagnitude2(v, s));
	r = r+(Normal2(v));
	r = r+(Lerp2(v, o, s));
	r = r+(Rot90CW2(v));
	r = r+(Rot90CCW2(v));
	r = r+(Rot2(v, s, o));
	r = r+(SetDim2(v, d, s));
	r = r+(AddDim2(v, d, s));
	r = r+(SubDim2(v, d, s));
	r = r+(MulDim2(v, d, s));
	r = r+(DivDim2(v, d, s));
	var sum = Length2(r);
	sum += LengthSquared2(r);
	sum += Dot2(v, o);
	sum += Cross2(v, o);
	sum += DistanceTo2(v, o);
	sum += DistanceToSquared2(v, o);
	sum += CosTo2(v, o);
	sum += AngleTo2(v, o);
	sum += Dim2(v, d);
	if (InTriangle2(v, o, v, o)) {
		sum += f32(1);
	}
	var nd = WindowToNDC2(v, o, v, true);
return sum + nd.x + nd.y + nd.z;
}
fn Vector3Test(v: vec3<f32>,o: vec3<f32>, s: f32, d: i32) -> f32 {
	var r = DivSafe3(v, o);
	r = r+(Negate3(v));
	r = r+(Max3(v, o));
	r = r+(Min3(v, o));
	r = r+(Abs3(v));
	r = r+(Floor3(v));
	r = r+(Ceil3(v));
	r = r+(Round3(v));
	r = r+(Clamp3(v, o, o));
	r = r+(ClampMagnitude3(v, s));
	r = r+(Normal3(v));
	r = r+(Cross3(v, o));
	r = r+(Lerp3(v, o, s));
	r = r+(ProjectOnVector3(v, o));
	r = r+(ProjectOnPlane3(v, o));
	r = r+(Reflect3(v, o));
	r = r+(SetDim3(v, d, s));
	r = r+(NDCToWindow3(v, vec2<f32>(v.x, v.y), vec2<f32>(o.x, o.y), s, s, true));
	r = r+(Vec3FromVec4(vec4<f32>(v.x, v.y, v.z, s)));
	var sum = Length3(r);
	sum += LengthSquared3(r);
	sum += Dot3(v, o);
	sum += DistanceTo3(v, o);
	sum += DistanceToSquared3(v, o);
	sum += CosTo3(v, o);
	sum += AngleTo3(v, o);
	sum += Dim3(v, d);
return sum;
}
fn Vector4Test(v: vec4<f32>,o: vec4<f32>, s: f32, d: i32) -> f32 {
	var r = DivSafe4(v, o);
	r = r+(Negate4(v));
	r = r+(Max4(v, o));
	r = r+(Min4(v, o));
	r = r+(Abs4(v));
	r = r+(Floor4(v));
	r = r+(Ceil4(v));
	r = r+(Round4(v));
	r = r+(Clamp4(v, o, o));
	r = r+(ClampMagnitude4(v, s));
	r = r+(Normal4(v));
	r = r+(Lerp4(v, o, s));
	r = r+(SetDim4(v, d, s));
	r = r+(Vec4FromVec3(vec3<f32>(v.x, v.y, v.z), s));
	var sum = Length4(r);
	sum += LengthSquared4(r);
	sum += Dot4(v, o);
	sum += Dim4(v, d);
	var pd = PerspDiv4(r);
return sum + pd.x + pd.y + pd.z;
}
fn Matrix2Test(v: vec2<f32>, s: f32) -> f32 {
	var m = Mat2Set(s, s, s, s, s, s);
	m = Mat2Mul(m, Mat2Identity());
	m = Mat2Mul(m, Mat2Translate2D(v.x, v.y));
	m = Mat2Mul(m, Mat2Scale2D(v.x, v.y));
	m = Mat2Mul(m, Mat2Rotate2D(s));
	m = Mat2Mul(m, Mat2Rotate2DAround(s, v));
	m = Mat2Mul(m, Mat2Shear2D(v.x, v.y));
	m = Mat2Mul(m, Mat2Skew2D(v.x, v.y));
	m = Mat2Translate(m, v.x, v.y);
	m = Mat2Scale(m, v.x, v.y);
	m = Mat2ScaleAbout(m, v.x, v.y, v.x, v.y);
	m = Mat2Rotate(m, s);
	m = Mat2RotateAbout(m, s, v.x, v.y);
	m = Mat2Shear(m, v.x, v.y);
	m = Mat2Skew(m, v.x, v.y);
	m = Mat2Transpose(m);
	m = Mat2Inverse(m);
	var r = Mat2MulVector(m, v);
	r = r+(Mat2MulPoint(m, v));
	r = r+(Mat2Pos(m));
	var sum = Mat2Det(m) + Mat2ExtractRot(m) + r.x + r.y;
	if (Mat2IsIdentity(m)) {
		sum += f32(1);
	}return sum;
}
fn Matrix3Test(v2: vec2<f32>, v3: vec3<f32>, q: vec4<f32>, s: f32) -> f32 {
	var m = Mat3Identity();
	m = Mat3Mul(m, Mat3FromMatrix2(Mat2Rotate2D(s)));
	m = Mat3Mul(m, Mat3FromMatrix4(Mat4Identity()));
	m = Mat3Mul(m, Mat3Translate2D(v2.x, v2.y));
	m = Mat3Mul(m, Mat3Scale2D(v2.x, v2.y));
	m = Mat3Mul(m, Mat3Rotate2D(s));
	m = Mat3Mul(m, QuatToMatrix3(q));
	m = Mat3MulScalar(m, s);
	m = Mat3Transpose(m);
	m = Mat3Inverse(m);
	m = Mat3ScaleCols(m, v3);
	m = Mat3NormalMatrix(Mat4Identity());
	var r2 = Mat3MulVector2(m, v2);
	r2 = r2+(Mat3MulPoint2(m, v2));
	var r3 = Mat3MulVector3(m, v3);
return Mat3Determinant(m) + r2.x + r2.y + r3.x + r3.y + r3.z;
}
fn Matrix4Test(v3: vec3<f32>, v4: vec4<f32>, q: vec4<f32>, s: f32) -> f32 {
	var m = Mat4Set(s, s, s, s, s, s, s, s, s, s, s, s, s, s, s, s);
	m = Mat4Mul(m, Mat4Identity());
	m = Mat4Mul(m, Mat4FromMatrix3(Mat3Identity()));
	m = Mat4Mul(m, Mat4Translate3D(v3.x, v3.y, v3.z));
	m = Mat4Mul(m, Mat4Scale3D(v3.x, v3.y, v3.z));
	m = Mat4Mul(m, Mat4RotateX(s));
	m = Mat4Mul(m, Mat4RotateY(s));
	m = Mat4Mul(m, Mat4RotateZ(s));
	m = Mat4Mul(m, Mat4RotateAxis(v3, s));
	m = Mat4Mul(m, Mat4SetBasis(v3, v3, v3));
	m = Mat4Mul(m, Mat4FromQuat(q));
	m = Mat4Mul(m, Mat4FromEuler(v3));
	m = Mat4Mul(m, Mat4Transform(v3, q, v3));
	m = Mat4MulScalar(m, s);
	m = Mat4Transpose(m);
	m = Mat4Inverse(m);
	m = Mat4ScaleCols(m, v3);
	m = Mat4SetPos(m, v3);
	m = Mat4CopyPos(m, Mat4Identity());
	m = Mat4ExtractRotation(m);
	var r3 = Mat4MulVector3(m, v3);
	r3 = r3+(Mat4MulVector3AsVector4(m, v3, s));
	r3 = r3+(Mat4MulProjection3(m, v3));
	r3 = r3+(Mat4Pos(m));
	r3 = r3+(Mat4ToEuler(m));
	var r4 = Mat4MulVector4(m, v4);
	var sum = Mat4Determinant(m) + Mat4MaxScaleOnAxis(m);
return sum + r3.x + r3.y + r3.z + r4.x + r4.y + r4.z + r4.w;
}
fn QuatTest(q: vec4<f32>,o: vec4<f32>, v: vec3<f32>, s: f32, d: i32) -> f32 {
	var r = QuatIdentity();
	r = QuatAdd(r, QuatNormalize(q));
	r = QuatAdd(r, QuatNormalizeFast(q));
	r = QuatAdd(r, QuatConjugate(q));
	r = QuatAdd(r, QuatInverse(q));
	r = QuatAdd(r, MulQuats(q, o));
	r = QuatAdd(r, QuatMulScalar(q, s));
	r = QuatAdd(r, QuatSetDim(q, d, s));
	r = QuatAdd(r, QuatFromEuler(v));
	r = QuatAdd(r, QuatFromAxisAngle(v, s));
	r = QuatAdd(r, QuatFromMatrix4(Mat4Identity()));
	r = QuatAdd(r, QuatFromUnitVectors(v, v));
	r = QuatAdd(r, QuatSlerp(q, o, s));
	var e = QuatToEuler(r);
	e = e+(EulerAnglesFromQuat(r));
	e = e+(MulQuatVector(r, v));
	e = e+(MulQuatVectorInverse(r, v));
	var aa = QuatToAxisAngle(r);
	var sum = QuatLength(r) + QuatLengthSquared(r);
	sum += QuatDot(q, o) + QuatDim(q, d);
	if (QuatIsIdentity(r)) {
		sum += f32(1);
	}
	if (QuatIsNil(r)) {
		sum += f32(1);
	}return sum + e.x + e.y + e.z + aa.x + aa.y + aa.z + aa.w;
}
fn SpatialTest(aP: vec3<f32>, aQ: vec4<f32>, bP: vec3<f32>, bQ: vec4<f32>) -> f32 {
	var oP: vec3<f32>;
	var oQ: vec4<f32>;
	MulSpatialTransforms(aP, aQ, bP, bQ, &oP, &oQ);
	var iP: vec3<f32>;
	var iQ: vec4<f32>;
	SpatialTransformInverse(oP, oQ, &iP, &iQ);
	var p = MulSpatialPoint(iP, iQ, bP);
return p.x + p.y + p.z + MinAngleDiff(aP.x, bP.x);
}
fn MatrixOpsTest(v3: vec3<f32>, s: f32, d: i32) -> f32 {
	var m3 = Mat3Rotate2D(s);
	var o3 = Mat3Scale2D(s, s);
	var r3 = (o3)*m3;
	r3 = r3*(s);
	var mv = r3*(v3);
	var r4 = Mat4MulScalar(Mat4Mul(Mat4RotateX(s), Mat4Scale3D(s, s, s)), s);
	var sum = r3[(d)/3][(d)%3] + r4[(d)/4][(d)%4];
return sum + mv.x + mv.y + mv.z;
}
fn SLMathTest(i: u32) { //gosl:kernel
	var s = Data[i].Val + Params[0].Val;
	var d = i32(i) % 2;
	var v2 = vec2<f32>(s, s+1);
	var o2 = vec2<f32>(s-1, s+2);
	var v3 = vec3<f32>(s, s+1, s+2);
	var o3 = vec3<f32>(s-1, s+2, s-3);
	var v4 = vec4<f32>(s, s+1, s+2, s+3);
	var o4 = vec4<f32>(s-1, s+2, s-3, s+4);
	var q = vec4<f32>(s, s+1, s+2, s+3);
	var p = vec4<f32>(s-1, s+2, s-3, s+4);
	var sum = Vector2Test(v2, o2, s, d);
	sum += Vector3Test(v3, o3, s, d);
	sum += Vector4Test(v4, o4, s, d);
	sum += Matrix2Test(v2, s);
	sum += Matrix3Test(v2, v3, q, s);
	sum += Matrix4Test(v3, v4, q, s);
	sum += QuatTest(q, p, v3, s, d);
	sum += SpatialTest(v3, q, o3, p);
	sum += MatrixOpsTest(v3, s, d);
	Data[i].Val = sum;
}

//////// import: "slmath-math.go"
const SLPi = 3.141592653589793;
fn MinAngleDiff(a: f32,b: f32) -> f32 {
	var d = a - b;
	if (d > SLPi) {
		d -= 2 * SLPi;
	}
	if (d < -SLPi) {
		d += 2 * SLPi;
	}return d;
}

//////// import: "slmath-matrix2.go"
fn Mat2Set(xx: f32,yx: f32,xy: f32,yy: f32,x0: f32,y0: f32) -> mat2x3f {
	var m: mat2x3f;
	m[0][0] = xx;
	m[1][0] = yx;
	m[0][1] = xy;
	m[1][1] = yy;
	m[0][2] = x0;
	m[1][2] = y0;
return m;
}
fn Mat2Identity() -> mat2x3f {
	return Mat2Set(f32(f32(1)), f32(f32(0)), f32(f32(0)), f32(f32(1)), f32(f32(0)), f32(f32(0)));
}
fn Mat2IsIdentity(m: mat2x3f) -> bool {
	return m[0][0] == 1 && m[1][0] == 0 && m[0][1] == 0 && m[1][1] == 1 && m[0][2] == 0 && m[1][2] == 0;
}
fn Mat2Translate2D(x: f32,y: f32) -> mat2x3f {
	return Mat2Set(f32(f32(1)), f32(f32(0)), f32(f32(0)), f32(f32(1)), x, y);
}
fn Mat2Scale2D(x: f32,y: f32) -> mat2x3f {
	return Mat2Set(x, f32(f32(0)), f32(f32(0)), y, f32(f32(0)), f32(f32(0)));
}
fn Mat2Rotate2D(angle: f32) -> mat2x3f {
	var s = sin(angle);
	var c = cos(angle);
return Mat2Set(c, s, -s, c, f32(f32(0)), f32(f32(0)));
}
fn Mat2Shear2D(x: f32,y: f32) -> mat2x3f {
	return Mat2Set(f32(f32(1)), y, x, f32(f32(1)), f32(f32(0)), f32(f32(0)));
}
fn Mat2Skew2D(x: f32,y: f32) -> mat2x3f {
	return Mat2Set(f32(f32(1)), tan(y), tan(x), f32(f32(1)), f32(f32(0)), f32(f32(0)));
}
fn Mat2Mul(a: mat2x3f,b: mat2x3f) -> mat2x3f {
	return Mat2Set(
		a[0][0]*b[0][0]+a[0][1]*b[1][0],
		a[1][0]*b[0][0]+a[1][1]*b[1][0],
		a[0][0]*b[0][1]+a[0][1]*b[1][1],
		a[1][0]*b[0][1]+a[1][1]*b[1][1],
		a[0][0]*b[0][2]+a[0][1]*b[1][2]+a[0][2],
		a[1][0]*b[0][2]+a[1][1]*b[1][2]+a[1][2]);
}
fn Mat2MulVector(a: mat2x3f, v: vec2<f32>) -> vec2<f32> {
	return vec2<f32>(a[0][0]*v.x+a[0][1]*v.y, a[1][0]*v.x+a[1][1]*v.y);
}
fn Mat2MulPoint(a: mat2x3f, v: vec2<f32>) -> vec2<f32> {
	return vec2<f32>(a[0][0]*v.x+a[0][1]*v.y+a[0][2], a[1][0]*v.x+a[1][1]*v.y+a[1][2]);
}
fn Mat2Translate(a: mat2x3f, x: f32,y: f32) -> mat2x3f {
	return Mat2Mul(a, Mat2Translate2D(x, y));
}
fn Mat2Scale(a: mat2x3f, x: f32,y: f32) -> mat2x3f {
	return Mat2Mul(a, Mat2Scale2D(x, y));
}
fn Mat2ScaleAbout(a: mat2x3f, sx: f32,sy: f32,x: f32,y: f32) -> mat2x3f {
	return Mat2Translate(Mat2Scale(Mat2Translate(a, x, y), sx, sy), -x, -y);
}
fn Mat2Rotate(a: mat2x3f, angle: f32) -> mat2x3f {
	return Mat2Mul(a, Mat2Rotate2D(angle));
}
fn Mat2RotateAbout(a: mat2x3f, rot: f32,x: f32,y: f32) -> mat2x3f {
	return Mat2Translate(Mat2Rotate(Mat2Translate(a, x, y), rot), -x, -y);
}
fn Mat2Rotate2DAround(angle: f32, pos: vec2<f32>) -> mat2x3f {
	return Mat2Translate(Mat2Rotate(Mat2Translate(Mat2Identity(), pos.x, pos.y), angle), -pos.x, -pos.y);
}
fn Mat2Shear(a: mat2x3f, x: f32,y: f32) -> mat2x3f {
	return Mat2Mul(a, Mat2Shear2D(x, y));
}
fn Mat2Skew(a: mat2x3f, x: f32,y: f32) -> mat2x3f {
	return Mat2Mul(a, Mat2Skew2D(x, y));
}
fn Mat2ExtractRot(a: mat2x3f) -> f32 {
	return atan2(-a[0][1], a[0][0]);
}
fn Mat2Pos(a: mat2x3f) -> vec2<f32> {
	return vec2<f32>(a[0][2], a[1][2]);
}
fn Mat2Transpose(a: mat2x3f) -> mat2x3f {
	return Mat2Set(a[0][0], a[0][1], a[1][0], a[1][1], a[0][2], a[1][2]);
}
fn Mat2Det(a: mat2x3f) -> f32 {
	return a[0][0]*a[1][1] - a[0][1]*a[1][0];
}
fn Mat2Inverse(a: mat2x3f) -> mat2x3f {
	var det = Mat2Det(a);
	if (det == 0) {
		return Mat2Identity();
	}
	var di = 1 / det;
return Mat2Set(
	a[1][1]*di,
	-a[1][0]*di,
	-a[0][1]*di,
	a[0][0]*di,
	(a[1][2]*a[0][1]-a[1][1]*a[0][2])*di,
	(a[0][2]*a[1][0]-a[0][0]*a[1][2])*di);
}

//////// import: "slmath-matrix3.go"
fn Mat3Identity() -> mat3x3f {
	return mat3x3f(
		1, 0, 0,
		0, 1, 0,
		0, 0, 1);
}
fn Mat3FromMatrix2(m: mat2x3f) -> mat3x3f {
	return mat3x3f(
		m[0][0], m[0][1], m[0][2],
		m[1][0], m[1][1], m[1][2],
		m[0][2], m[1][2], 1);
}
fn Mat3FromMatrix4(m: mat4x4f) -> mat3x3f {
	return mat3x3f(
		m[0][0], m[0][1], m[0][2],
		m[1][0], m[1][1], m[1][2],
		m[2][0], m[2][1], m[2][2]);
}
fn Mat3Translate2D(x: f32,y: f32) -> mat3x3f {
	return Mat3FromMatrix2(Mat2Translate2D(x, y));
}
fn Mat3Scale2D(x: f32,y: f32) -> mat3x3f {
	return Mat3FromMatrix2(Mat2Scale2D(x, y));
}
fn Mat3Rotate2D(angle: f32) -> mat3x3f {
	return Mat3FromMatrix2(Mat2Rotate2D(angle));
}
fn Mat3Mul(a: mat3x3f,b: mat3x3f) -> mat3x3f {
	return mat3x3f(
		b[0][0]*a[0][0]+b[1][0]*a[0][1]+b[2][0]*a[0][2],
		b[0][1]*a[0][0]+b[1][1]*a[0][1]+b[2][1]*a[0][2],
		b[0][2]*a[0][0]+b[1][2]*a[0][1]+b[2][2]*a[0][2],
		b[0][0]*a[1][0]+b[1][0]*a[1][1]+b[2][0]*a[1][2],
		b[0][1]*a[1][0]+b[1][1]*a[1][1]+b[2][1]*a[1][2],
		b[0][2]*a[1][0]+b[1][2]*a[1][1]+b[2][2]*a[1][2],
		b[0][0]*a[2][0]+b[1][0]*a[2][1]+b[2][0]*a[2][2],
		b[0][1]*a[2][0]+b[1][1]*a[2][1]+b[2][1]*a[2][2],
		b[0][2]*a[2][0]+b[1][2]*a[2][1]+b[2][2]*a[2][2]);
}
fn Mat3MulScalar(m: mat3x3f, s: f32) -> mat3x3f {
	return mat3x3f(
		m[0][0]*s, m[0][1]*s, m[0][2]*s,
		m[1][0]*s, m[1][1]*s, m[1][2]*s,
		m[2][0]*s, m[2][1]*s, m[2][2]*s);
}
fn Mat3MulVector2(a: mat3x3f, v: vec2<f32>) -> vec2<f32> {
	return vec2<f32>(a[0][0]*v.x+a[0][1]*v.y, a[1][0]*v.x+a[1][1]*v.y);
}
fn Mat3MulPoint2(a: mat3x3f, v: vec2<f32>) -> vec2<f32> {
	return vec2<f32>(a[0][0]*v.x+a[0][1]*v.y+a[0][2], a[1][0]*v.x+a[1][1]*v.y+a[1][2]);
}
fn Mat3MulVector3(a: mat3x3f, v: vec3<f32>) -> vec3<f32> {
	return vec3<f32>(
		a[0][0]*v.x+a[1][0]*v.y+a[2][0]*v.z,
		a[0][1]*v.x+a[1][1]*v.y+a[2][1]*v.z,
		a[0][2]*v.x+a[1][2]*v.y+a[2][2]*v.z);
}
fn Mat3Determinant(m: mat3x3f) -> f32 {
	return m[0][0]*m[1][1]*m[2][2] -
		m[0][0]*m[1][2]*m[2][1] -
		m[0][1]*m[1][0]*m[2][2] +
		m[0][1]*m[1][2]*m[2][0] +
		m[0][2]*m[1][0]*m[2][1] -
		m[0][2]*m[1][1]*m[2][0];
}
fn Mat3Inverse(m: mat3x3f) -> mat3x3f {
	var n11 = m[0][0];
	var n21 = m[0][1];
	var n31 = m[0][2];
	var n12 = m[1][0];
	var n22 = m[1][1];
	var n32 = m[1][2];
	var n13 = m[2][0];
	var n23 = m[2][1];
	var n33 = m[2][2];
	var t11 = n33*n22 - n32*n23;
	var t12 = n32*n13 - n33*n12;
	var t13 = n23*n12 - n22*n13;
	var det = n11*t11 + n21*t12 + n31*t13;
	if (det == 0) {
		return Mat3Identity();
	}
	var di = 1 / det;
return mat3x3f(
	t11*di,
	(n31*n23-n33*n21)*di,
	(n32*n21-n31*n22)*di,
	t12*di,
	(n33*n11-n31*n13)*di,
	(n31*n12-n32*n11)*di,
	t13*di,
	(n21*n13-n23*n11)*di,
	(n22*n11-n21*n12)*di);
}
fn Mat3Transpose(m: mat3x3f) -> mat3x3f {
	return mat3x3f(
		m[0][0], m[1][0], m[2][0],
		m[0][1], m[1][1], m[2][1],
		m[0][2], m[1][2], m[2][2]);
}
fn Mat3ScaleCols(m: mat3x3f, v: vec3<f32>) -> mat3x3f {
	return mat3x3f(
		m[0][0]*v.x, m[0][1]*v.x, m[0][2]*v.x,
		m[1][0]*v.y, m[1][1]*v.y, m[1][2]*v.y,
		m[2][0]*v.z, m[2][1]*v.z, m[2][2]*v.z);
}
fn Mat3NormalMatrix(m: mat4x4f) -> mat3x3f {
	return Mat3Transpose(Mat3Inverse(Mat3FromMatrix4(m)));
}

//////// import: "slmath-matrix4.go"
fn Mat4Set(n11: f32,n12: f32,n13: f32,n14: f32,n21: f32,n22: f32,n23: f32,n24: f32,n31: f32,n32: f32,n33: f32,n34: f32,n41: f32,n42: f32,n43: f32,n44: f32) -> mat4x4f {
	var m: mat4x4f;
	m[0][0] = n11;
	m[1][0] = n12;
	m[2][0] = n13;
	m[3][0] = n14;
	m[0][1] = n21;
	m[1][1] = n22;
	m[2][1] = n23;
	m[3][1] = n24;
	m[0][2] = n31;
	m[1][2] = n32;
	m[2][2] = n33;
	m[3][2] = n34;
	m[0][3] = n41;
	m[1][3] = n42;
	m[2][3] = n43;
	m[3][3] = n44;
return m;
}
fn Mat4Identity() -> mat4x4f {
	return Mat4Set(
		f32(f32(1)), f32(f32(0)), f32(f32(0)), f32(f32(0)),
		f32(f32(0)), f32(f32(1)), f32(f32(0)), f32(f32(0)),
		f32(f32(0)), f32(f32(0)), f32(f32(1)), f32(f32(0)),
		f32(f32(0)), f32(f32(0)), f32(f32(0)), f32(f32(1)));
}
fn Mat4FromMatrix3(s: mat3x3f) -> mat4x4f {
	return Mat4Set(
		s[0][0], s[1][0], s[2][0], f32(f32(0)),
		s[0][1], s[1][1], s[2][1], f32(f32(0)),
		s[0][2], s[1][2], s[2][2], f32(f32(0)),
		f32(f32(0)), f32(f32(0)), f32(f32(0)), f32(f32(1)));
}
fn Mat4Mul(a: mat4x4f,b: mat4x4f) -> mat4x4f {
	var a11 = a[0][0];
	var a12 = a[1][0];
	var a13 = a[2][0];
	var a14 = a[3][0];
	var a21 = a[0][1];
	var a22 = a[1][1];
	var a23 = a[2][1];
	var a24 = a[3][1];
	var a31 = a[0][2];
	var a32 = a[1][2];
	var a33 = a[2][2];
	var a34 = a[3][2];
	var a41 = a[0][3];
	var a42 = a[1][3];
	var a43 = a[2][3];
	var a44 = a[3][3];
	var b11 = b[0][0];
	var b12 = b[1][0];
	var b13 = b[2][0];
	var b14 = b[3][0];
	var b21 = b[0][1];
	var b22 = b[1][1];
	var b23 = b[2][1];
	var b24 = b[3][1];
	var b31 = b[0][2];
	var b32 = b[1][2];
	var b33 = b[2][2];
	var b34 = b[3][2];
	var b41 = b[0][3];
	var b42 = b[1][3];
	var b43 = b[2][3];
	var b44 = b[3][3];
return Mat4Set(
	a11*b11+a12*b21+a13*b31+a14*b41,
	a11*b12+a12*b22+a13*b32+a14*b42,
	a11*b13+a12*b23+a13*b33+a14*b43,
	a11*b14+a12*b24+a13*b34+a14*b44,
	a21*b11+a22*b21+a23*b31+a24*b41,
	a21*b12+a22*b22+a23*b32+a24*b42,
	a21*b13+a22*b23+a23*b33+a24*b43,
	a21*b14+a22*b24+a23*b34+a24*b44,
	a31*b11+a32*b21+a33*b31+a34*b41,
	a31*b12+a32*b22+a33*b32+a34*b42,
	a31*b13+a32*b23+a33*b33+a34*b43,
	a31*b14+a32*b24+a33*b34+a34*b44,
	a41*b11+a42*b21+a43*b31+a44*b41,
	a41*b12+a42*b22+a43*b32+a44*b42,
	a41*b13+a42*b23+a43*b33+a44*b43,
	a41*b14+a42*b24+a43*b34+a44*b44);
}
fn Mat4MulScalar(m: mat4x4f, s: f32) -> mat4x4f {
	return Mat4Set(
		m[0][0]*s, m[1][0]*s, m[2][0]*s, m[3][0]*s,
		m[0][1]*s, m[1][1]*s, m[2][1]*s, m[3][1]*s,
		m[0][2]*s, m[1][2]*s, m[2][2]*s, m[3][2]*s,
		m[0][3]*s, m[1][3]*s, m[2][3]*s, m[3][3]*s);
}
fn Mat4MulVector3(m: mat4x4f, v: vec3<f32>) -> vec3<f32> {
	return vec3<f32>(
		m[0][0]*v.x+m[1][0]*v.y+m[2][0]*v.z+m[3][0],
		m[0][1]*v.x+m[1][1]*v.y+m[2][1]*v.z+m[3][1],
		m[0][2]*v.x+m[1][2]*v.y+m[2][2]*v.z+m[3][2]);
}
fn Mat4MulVector4(m: mat4x4f, v: vec4<f32>) -> vec4<f32> {
	return vec4<f32>(
		m[0][0]*v.x+m[1][0]*v.y+m[2][0]*v.z+m[3][0]*v.w,
		m[0][1]*v.x+m[1][1]*v.y+m[2][1]*v.z+m[3][1]*v.w,
		m[0][2]*v.x+m[1][2]*v.y+m[2][2]*v.z+m[3][2]*v.w,
		m[0][3]*v.x+m[1][3]*v.y+m[2][3]*v.z+m[3][3]*v.w);
}
fn Mat4MulVector3AsVector4(m: mat4x4f, v: vec3<f32>, w: f32) -> vec3<f32> {
	return Vec3FromVec4(Mat4MulVector4(m, Vec4FromVec3(v, w)));
}
fn Mat4MulProjection3(m: mat4x4f, v: vec3<f32>) -> vec3<f32> {
	var d = 1 / (m[0][3]*v.x + m[1][3]*v.y + m[2][3]*v.z + m[3][3]); // perspective divide
return vec3<f32>(
	(m[0][0]*v.x+m[1][0]*v.y+m[2][0]*v.z+m[3][0])*d,
	(m[0][1]*v.x+m[1][1]*v.y+m[2][1]*v.z+m[3][1])*d,
	(m[0][2]*v.x+m[1][2]*v.y+m[2][2]*v.z+m[3][2])*d);
}
fn Mat4Determinant(m: mat4x4f) -> f32 {
	var n11 = m[0][0];
	var n12 = m[1][0];
	var n13 = m[2][0];
	var n14 = m[3][0];
	var n21 = m[0][1];
	var n22 = m[1][1];
	var n23 = m[2][1];
	var n24 = m[3][1];
	var n31 = m[0][2];
	var n32 = m[1][2];
	var n33 = m[2][2];
	var n34 = m[3][2];
	var n41 = m[0][3];
	var n42 = m[1][3];
	var n43 = m[2][3];
	var n44 = m[3][3];
return n41*(n14*n23*n32-n13*n24*n32-n14*n22*n33+n12*n24*n33+n13*n22*n34-n12*n23*n34) +
	n42*(n11*n23*n34-n11*n24*n33+n14*n21*n33-n13*n21*n34+n13*n24*n31-n14*n23*n31) +
	n43*(n11*n24*n32-n11*n22*n34-n14*n21*n32+n12*n21*n34+n14*n22*n31-n12*n24*n31) +
	n44*(0-n13*n22*n31-n11*n23*n32+n11*n22*n33+n13*n21*n32-n12*n21*n33+n12*n23*n31);
}
fn Mat4Inverse(s: mat4x4f) -> mat4x4f {
	var n11 = s[0][0];
	var n12 = s[1][0];
	var n13 = s[2][0];
	var n14 = s[3][0];
	var n21 = s[0][1];
	var n22 = s[1][1];
	var n23 = s[2][1];
	var n24 = s[3][1];
	var n31 = s[0][2];
	var n32 = s[1][2];
	var n33 = s[2][2];
	var n34 = s[3][2];
	var n41 = s[0][3];
	var n42 = s[1][3];
	var n43 = s[2][3];
	var n44 = s[3][3];
	var t11 = n23*n34*n42 - n24*n33*n42 + n24*n32*n43 - n22*n34*n43 - n23*n32*n44 + n22*n33*n44;
	var t12 = n14*n33*n42 - n13*n34*n42 - n14*n32*n43 + n12*n34*n43 + n13*n32*n44 - n12*n33*n44;
	var t13 = n13*n24*n42 - n14*n23*n42 + n14*n22*n43 - n12*n24*n43 - n13*n22*n44 + n12*n23*n44;
	var t14 = n14*n23*n32 - n13*n24*n32 - n14*n22*n33 + n12*n24*n33 + n13*n22*n34 - n12*n23*n34;
	var det = n11*t11 + n21*t12 + n31*t13 + n41*t14;
	if (det == 0) {
		return Mat4Identity();
	}
	var di = 1 / det;
	var m: mat4x4f;
	m[0][0] = t11 * di;
	m[0][1] = (n24*n33*n41 - n23*n34*n41 - n24*n31*n43 + n21*n34*n43 + n23*n31*n44 - n21*n33*n44) * di;
	m[0][2] = (n22*n34*n41 - n24*n32*n41 + n24*n31*n42 - n21*n34*n42 - n22*n31*n44 + n21*n32*n44) * di;
	m[0][3] = (n23*n32*n41 - n22*n33*n41 - n23*n31*n42 + n21*n33*n42 + n22*n31*n43 - n21*n32*n43) * di;
	m[1][0] = t12 * di;
	m[1][1] = (n13*n34*n41 - n14*n33*n41 + n14*n31*n43 - n11*n34*n43 - n13*n31*n44 + n11*n33*n44) * di;
	m[1][2] = (n14*n32*n41 - n12*n34*n41 - n14*n31*n42 + n11*n34*n42 + n12*n31*n44 - n11*n32*n44) * di;
	m[1][3] = (n12*n33*n41 - n13*n32*n41 + n13*n31*n42 - n11*n33*n42 - n12*n31*n43 + n11*n32*n43) * di;
	m[2][0] = t13 * di;
	m[2][1] = (n14*n23*n41 - n13*n24*n41 - n14*n21*n43 + n11*n24*n43 + n13*n21*n44 - n11*n23*n44) * di;
	m[2][2] = (n12*n24*n41 - n14*n22*n41 + n14*n21*n42 - n11*n24*n42 - n12*n21*n44 + n11*n22*n44) * di;
	m[2][3] = (n13*n22*n41 - n12*n23*n41 - n13*n21*n42 + n11*n23*n42 + n12*n21*n43 - n11*n22*n43) * di;
	m[3][0] = t14 * di;
	m[3][1] = (n13*n24*n31 - n14*n23*n31 + n14*n21*n33 - n11*n24*n33 - n13*n21*n34 + n11*n23*n34) * di;
	m[3][2] = (n14*n22*n31 - n12*n24*n31 - n14*n21*n32 + n11*n24*n32 + n12*n21*n34 - n11*n22*n34) * di;
	m[3][3] = (n12*n23*n31 - n13*n22*n31 + n13*n21*n32 - n11*n23*n32 - n12*n21*n33 + n11*n22*n33) * di;
return m;
}
fn Mat4Transpose(m: mat4x4f) -> mat4x4f {
	return Mat4Set(
		m[0][0], m[0][1], m[0][2], m[0][3],
		m[1][0], m[1][1], m[1][2], m[1][3],
		m[2][0], m[2][1], m[2][2], m[2][3],
		m[3][0], m[3][1], m[3][2], m[3][3]);
}
fn Mat4ScaleCols(m: mat4x4f, v: vec3<f32>) -> mat4x4f {
	return Mat4Set(
		m[0][0]*v.x, m[1][0]*v.y, m[2][0]*v.z, m[3][0],
		m[0][1]*v.x, m[1][1]*v.y, m[2][1]*v.z, m[3][1],
		m[0][2]*v.x, m[1][2]*v.y, m[2][2]*v.z, m[3][2],
		m[0][3]*v.x, m[1][3]*v.y, m[2][3]*v.z, m[3][3]);
}
fn Mat4MaxScaleOnAxis(m: mat4x4f) -> f32 {
	var sx = m[0][0]*m[0][0] + m[0][1]*m[0][1] + m[0][2]*m[0][2];
	var sy = m[1][0]*m[1][0] + m[1][1]*m[1][1] + m[1][2]*m[1][2];
	var sz = m[2][0]*m[2][0] + m[2][1]*m[2][1] + m[2][2]*m[2][2];
return sqrt(max(sx, max(sy, sz)));
}
fn Mat4Translate3D(x: f32,y: f32,z: f32) -> mat4x4f {
	return Mat4Set(
		f32(f32(1)), f32(f32(0)), f32(f32(0)), x,
		f32(f32(0)), f32(f32(1)), f32(f32(0)), y,
		f32(f32(0)), f32(f32(0)), f32(f32(1)), z,
		f32(f32(0)), f32(f32(0)), f32(f32(0)), f32(f32(1)));
}
fn Mat4Scale3D(x: f32,y: f32,z: f32) -> mat4x4f {
	return Mat4Set(
		x, f32(f32(0)), f32(f32(0)), f32(f32(0)),
		f32(f32(0)), y, f32(f32(0)), f32(f32(0)),
		f32(f32(0)), f32(f32(0)), z, f32(f32(0)),
		f32(f32(0)), f32(f32(0)), f32(f32(0)), f32(f32(1)));
}
fn Mat4RotateX(theta: f32) -> mat4x4f {
	var c = cos(theta);
	var s = sin(theta);
return Mat4Set(
	f32(f32(1)), f32(f32(0)), f32(f32(0)), f32(f32(0)),
	f32(f32(0)), c, -s, f32(f32(0)),
	f32(f32(0)), s, c, f32(f32(0)),
	f32(f32(0)), f32(f32(0)), f32(f32(0)), f32(f32(1)));
}
fn Mat4RotateY(theta: f32) -> mat4x4f {
	var c = cos(theta);
	var s = sin(theta);
return Mat4Set(
	c, f32(f32(0)), s, f32(f32(0)),
	f32(f32(0)), f32(f32(1)), f32(f32(0)), f32(f32(0)),
	-s, f32(f32(0)), c, f32(f32(0)),
	f32(f32(0)), f32(f32(0)), f32(f32(0)), f32(f32(1)));
}
fn Mat4RotateZ(theta: f32) -> mat4x4f {
	var c = cos(theta);
	var s = sin(theta);
return Mat4Set(
	c, -s, f32(f32(0)), f32(f32(0)),
	s, c, f32(f32(0)), f32(f32(0)),
	f32(f32(0)), f32(f32(0)), f32(f32(1)), f32(f32(0)),
	f32(f32(0)), f32(f32(0)), f32(f32(0)), f32(f32(1)));
}
fn Mat4RotateAxis(axis: vec3<f32>, angle: f32) -> mat4x4f {
	var c = cos(angle);
	var s = sin(angle);
	var t = 1 - c;
	var x = axis.x;
	var y = axis.y;
	var z = axis.z;
	var tx = t * x;
	var ty = t * y;
return Mat4Set(
	tx*x+c, tx*y-s*z, tx*z+s*y, f32(f32(0)),
	tx*y+s*z, ty*y+c, ty*z-s*x, f32(f32(0)),
	tx*z-s*y, ty*z+s*x, t*z*z+c, f32(f32(0)),
	f32(f32(0)), f32(f32(0)), f32(f32(0)), f32(f32(1)));
}
fn Mat4SetBasis(xAxis: vec3<f32>,yAxis: vec3<f32>,zAxis: vec3<f32>) -> mat4x4f {
	return Mat4Set(
		xAxis.x, yAxis.x, zAxis.x, f32(f32(0)),
		xAxis.y, yAxis.y, zAxis.y, f32(f32(0)),
		xAxis.z, yAxis.z, zAxis.z, f32(f32(0)),
		f32(f32(0)), f32(f32(0)), f32(f32(0)), f32(f32(1)));
}
fn Mat4Pos(m: mat4x4f) -> vec3<f32> {
	return vec3<f32>(m[3][0], m[3][1], m[3][2]);
}
fn Mat4SetPos(m: mat4x4f, v: vec3<f32>) -> mat4x4f {
	var nm = m;
	nm[3][0] = v.x;
	nm[3][1] = v.y;
	nm[3][2] = v.z;
return nm;
}
fn Mat4CopyPos(m: mat4x4f,src: mat4x4f) -> mat4x4f {
	var nm = m;
	nm[3][0] = src[3][0];
	nm[3][1] = src[3][1];
	nm[3][2] = src[3][2];
return nm;
}
fn Mat4FromQuat(q: vec4<f32>) -> mat4x4f {
	var x2 = q.x + q.x;
	var y2 = q.y + q.y;
	var z2 = q.z + q.z;
	var xx = q.x * x2;
	var xy = q.x * y2;
	var xz = q.x * z2;
	var yy = q.y * y2;
	var yz = q.y * z2;
	var zz = q.z * z2;
	var wx = q.w * x2;
	var wy = q.w * y2;
	var wz = q.w * z2;
return Mat4Set(
	1-(yy+zz), xy-wz, xz+wy, f32(f32(0)),
	xy+wz, 1-(xx+zz), yz-wx, f32(f32(0)),
	xz-wy, yz+wx, 1-(xx+yy), f32(f32(0)),
	f32(f32(0)), f32(f32(0)), f32(f32(0)), f32(f32(1)));
}
fn Mat4FromEuler(euler: vec3<f32>) -> mat4x4f {
	var a = cos(euler.x);
	var b = sin(euler.x);
	var c = cos(euler.y);
	var d = sin(euler.y);
	var e = cos(euler.z);
	var f = sin(euler.z);
	var ae = a * e;
	var af = a * f;
	var be = b * e;
	var bf = b * f;
return Mat4Set(
	c*e, -c*f, d, f32(f32(0)),
	af+be*d, ae-bf*d, -b*c, f32(f32(0)),
	bf-ae*d, be+af*d, a*c, f32(f32(0)),
	f32(f32(0)), f32(f32(0)), f32(f32(0)), f32(f32(1)));
}
fn Mat4ToEuler(m: mat4x4f) -> vec3<f32> {
	var m11 = m[0][0];
	var m12 = m[1][0];
	var m13 = m[2][0];
	var m22 = m[1][1];
	var m23 = m[2][1];
	var m32 = m[1][2];
	var m33 = m[2][2];
	var v: vec3<f32>;
	v.y = asin(clamp(m13, f32(-1), f32(1)));
	if (abs(m13) < 0.99999) {
		v.x = atan2(-m23, m33);
		v.z = atan2(-m12, m11);
	} else {
		v.x = atan2(m32, m22);
		v.z = f32(0);
	}return v;
}
fn Mat4Transform(pos: vec3<f32>, quat: vec4<f32>, scale: vec3<f32>) -> mat4x4f {
	return Mat4SetPos(Mat4ScaleCols(Mat4FromQuat(quat), scale), pos);
}
fn Mat4ExtractRotation(s: mat4x4f) -> mat4x4f {
	var sx = 1 / Length3(vec3<f32>(s[0][0], s[0][1], s[0][2]));
	var sy = 1 / Length3(vec3<f32>(s[1][0], s[1][1], s[1][2]));
	var sz = 1 / Length3(vec3<f32>(s[2][0], s[2][1], s[2][2]));
return Mat4Set(
	s[0][0]*sx, s[1][0]*sy, s[2][0]*sz, f32(f32(0)),
	s[0][1]*sx, s[1][1]*sy, s[2][1]*sz, f32(f32(0)),
	s[0][2]*sx, s[1][2]*sy, s[2][2]*sz, f32(f32(0)),
	f32(f32(0)), f32(f32(0)), f32(f32(0)), f32(f32(1)));
}

//////// import: "slmath-quaternion.go"
fn QuatLength(q: vec4<f32>) -> f32 {
	return sqrt(q.x*q.x + q.y*q.y + q.z*q.z + q.w*q.w);
}
fn QuatNormalize(q: vec4<f32>) -> vec4<f32> {
	var nq = q;
	var l = QuatLength(q);
	if (l == 0) {
		nq.x = f32(0);
		nq.y = f32(0);
		nq.z = f32(0);
		nq.w = f32(1);
	} else {
		l = 1 / l;
		nq.x *= l;
		nq.y *= l;
		nq.z *= l;
		nq.w *= l;
	}return nq;
}
fn MulQuatVector(q: vec4<f32>, v: vec3<f32>) -> vec3<f32> {
	var xyz = vec3<f32>(q.x, q.y, q.z);
	var t = Cross3(xyz, v)*(2);
return v+(t*(q.w))+(Cross3(xyz, t));
}
fn MulQuatVectorInverse(q: vec4<f32>, v: vec3<f32>) -> vec3<f32> {
	var xyz = vec3<f32>(q.x, q.y, q.z);
	var t = Cross3(xyz, v)*(2);
return v-(t*(q.w))+(Cross3(xyz, t));
}
fn MulQuats(a: vec4<f32>,b: vec4<f32>) -> vec4<f32> {
	var q: vec4<f32>;
	q.x = a.x*b.w + a.w*b.x + a.y*b.z - a.z*b.y;
	q.y = a.y*b.w + a.w*b.y + a.z*b.x - a.x*b.z;
	q.z = a.z*b.w + a.w*b.z + a.x*b.y - a.y*b.x;
	q.w = a.w*b.w - a.x*b.x - a.y*b.y - a.z*b.z;
return q;
}
fn MulSpatialTransforms(aP: vec3<f32>, aQ: vec4<f32>, bP: vec3<f32>, bQ: vec4<f32>, oP: ptr<function,vec3<f32>>, oQ: ptr<function,vec4<f32>>) {
	*oP = MulQuatVector(aQ, bP)+(aP);
	*oQ = MulQuats(aQ, bQ);
}
fn MulSpatialPoint(xP: vec3<f32>, xQ: vec4<f32>, p: vec3<f32>) -> vec3<f32> {
	var dp = MulQuatVector(xQ, p);
return dp+(xP);
}
fn SpatialTransformInverse(p: vec3<f32>, q: vec4<f32>, oP: ptr<function,vec3<f32>>, oQ: ptr<function,vec4<f32>>) {
	var qi = QuatInverse(q);
	*oP = Negate3(MulQuatVector(qi, p));
	*oQ = qi;
}
fn QuatInverse(q: vec4<f32>) -> vec4<f32> {
	var nq = q;
	nq.x *= f32(-1);
	nq.y *= f32(-1);
	nq.z *= f32(-1);
return QuatNormalize(nq);
}
fn QuatDot(q: vec4<f32>,o: vec4<f32>) -> f32 {
	return q.x*o.x + q.y*o.y + q.z*o.z + q.w*o.w;
}
fn QuatAdd(q: vec4<f32>, o: vec4<f32>) -> vec4<f32> {
	var nq = q;
	nq.x += o.x;
	nq.y += o.y;
	nq.z += o.z;
	nq.w += o.w;
return nq;
}
fn QuatMulScalar(q: vec4<f32>, s: f32) -> vec4<f32> {
	var nq = q;
	nq.x *= s;
	nq.y *= s;
	nq.z *= s;
	nq.w *= s;
return nq;
}
fn QuatDim(v: vec4<f32>, dim: i32) -> f32 {
	if (dim == 0) {
		return v.x;
	}
	if (dim == 1) {
		return v.y;
	}
	if (dim == 2) {
		return v.z;
	}return v.w;
}
fn QuatSetDim(v: vec4<f32>, dim: i32, val: f32) -> vec4<f32> {
	var nv = v;
	if (dim == 0) {
		nv.x = val;
	}
	if (dim == 1) {
		nv.y = val;
	}
	if (dim == 2) {
		nv.z = val;
	}
	if (dim == 3) {
		nv.w = val;
	}return nv;
}
fn QuatToMatrix3(q: vec4<f32>) -> mat3x3f {
	var m: mat3x3f;
	var x = q.x;
	var y = q.y;
	var z = q.z;
	var w = q.w;
	var x2 = x + x;
	var y2 = y + y;
	var z2 = z + z;
	var xx = x * x2;
	var xy = x * y2;
	var xz = x * z2;
	var yy = y * y2;
	var yz = y * z2;
	var zz = z * z2;
	var wx = w * x2;
	var wy = w * y2;
	var wz = w * z2;
	m[0][0] = 1 - (yy + zz);
	m[1][0] = xy - wz;
	m[2][0] = xz + wy;
	m[0][1] = xy + wz;
	m[1][1] = 1 - (xx + zz);
	m[2][1] = yz - wx;
	m[0][2] = xz - wy;
	m[1][2] = yz + wx;
	m[2][2] = 1 - (xx + yy);
return m;
}
fn QuatIdentity() -> vec4<f32> {
	return vec4<f32>(0, 0, 0, 1);
}
fn QuatIsIdentity(q: vec4<f32>) -> bool {
	return q.x == 0 && q.y == 0 && q.z == 0 && q.w == 1;
}
fn QuatIsNil(q: vec4<f32>) -> bool {
	return q.x == 0 && q.y == 0 && q.z == 0 && q.w == 0;
}
fn QuatLengthSquared(q: vec4<f32>) -> f32 {
	return q.x*q.x + q.y*q.y + q.z*q.z + q.w*q.w;
}
fn QuatConjugate(q: vec4<f32>) -> vec4<f32> {
	return vec4<f32>(-q.x, -q.y, -q.z, q.w);
}
fn QuatNormalizeFast(q: vec4<f32>) -> vec4<f32> {
	var f = (3 - QuatLengthSquared(q)) / 2;
	if (f == 0) {
		return QuatIdentity();
	}return QuatMulScalar(q, f);
}
fn QuatFromEuler(euler: vec3<f32>) -> vec4<f32> {
	var c1 = cos(euler.x / 2);
	var c2 = cos(euler.y / 2);
	var c3 = cos(euler.z / 2);
	var s1 = sin(euler.x / 2);
	var s2 = sin(euler.y / 2);
	var s3 = sin(euler.z / 2);
return vec4<f32>(
	s1*c2*c3-c1*s2*s3,
	c1*s2*c3+s1*c2*s3,
	c1*c2*s3-s1*s2*c3,
	c1*c2*c3+s1*s2*s3);
}
fn QuatToEuler(q: vec4<f32>) -> vec3<f32> {
	var x = MulQuatVector(q, vec3<f32>(1, 0, 0));
	var y = MulQuatVector(q, vec3<f32>(0, 1, 0));
	var z = MulQuatVector(q, vec3<f32>(0, 0, 1));
	var phi = atan2(z.y, z.z);
	var sinp = -z.x;
	var theta: f32;
	if (abs(sinp) >= 1) {
		theta = 0.5 * SLPi * sign(sinp);
	} else {
		theta = asin(sinp);
	}
	var psi = atan2(y.x, x.x);
return vec3<f32>(-phi, -theta, -psi);
}
fn EulerAnglesFromQuat(q: vec4<f32>) -> vec3<f32> {
	return Mat4ToEuler(Mat4FromQuat(q));
}
fn QuatFromAxisAngle(axis: vec3<f32>, angle: f32) -> vec4<f32> {
	var ha = angle / 2;
	var s = sin(ha);
return vec4<f32>(axis.x*s, axis.y*s, axis.z*s, cos(ha));
}
fn QuatToAxisAngle(q: vec4<f32>) -> vec4<f32> {
	var qw = clamp(q.w, f32(-1), f32(1));
	var w = 2 * acos(qw);
	var s = sqrt(1 - qw*qw);
	if (s < 0.0001) {
		return vec4<f32>(1, 0, 0, w);
	}return vec4<f32>(q.x/s, q.y/s, q.z/s, w);
}
fn QuatFromMatrix4(m: mat4x4f) -> vec4<f32> {
	var m11 = m[0][0];
	var m12 = m[1][0];
	var m13 = m[2][0];
	var m21 = m[0][1];
	var m22 = m[1][1];
	var m23 = m[2][1];
	var m31 = m[0][2];
	var m32 = m[1][2];
	var m33 = m[2][2];
	var trace = m11 + m22 + m33;
	var q: vec4<f32>;
	var s: f32;
	if (trace > 0) {
		s = 0.5 / sqrt(trace+1);
		q.w = 0.25 / s;
		q.x = (m32 - m23) * s;
		q.y = (m13 - m31) * s;
		q.z = (m21 - m12) * s;
	} else if (m11 > m22 && m11 > m33) {
		s = 2 * sqrt(1+m11-m22-m33);
		q.w = (m32 - m23) / s;
		q.x = 0.25 * s;
		q.y = (m12 + m21) / s;
		q.z = (m13 + m31) / s;
	} else if (m22 > m33) {
		s = 2 * sqrt(1+m22-m11-m33);
		q.w = (m13 - m31) / s;
		q.x = (m12 + m21) / s;
		q.y = 0.25 * s;
		q.z = (m23 + m32) / s;
	} else {
		s = 2 * sqrt(1+m33-m11-m22);
		q.w = (m21 - m12) / s;
		q.x = (m13 + m31) / s;
		q.y = (m23 + m32) / s;
		q.z = 0.25 * s;
	}return q;
}
fn QuatFromUnitVectors(vFrom: vec3<f32>,vTo: vec3<f32>) -> vec4<f32> {
	var v1: vec3<f32>;
	var r = Dot3(vFrom, vTo) + 1;
	if (r < 0.000001) {
		r = f32(0);
		if (abs(vFrom.x) > abs(vFrom.z)) {
			v1 = vec3<f32>(-vFrom.y, vFrom.x, 0);
		} else {
			v1 = vec3<f32>(0, -vFrom.z, vFrom.y);
		}
	} else {
		v1 = Cross3(vFrom, vTo);
	}return QuatNormalize(vec4<f32>(v1.x, v1.y, v1.z, r));
}
fn QuatSlerp(q: vec4<f32>,o: vec4<f32>, t: f32) -> vec4<f32> {
	if (t == 0) {
		return q;
	}
	if (t == 1) {
		return o;
	}
	var x = q.x;
	var y = q.y;
	var z = q.z;
	var w = q.w;
	var cosHalfTheta = w*o.w + x*o.x + y*o.y + z*o.z;
	var nq = o;
	if (cosHalfTheta < 0) {
		nq.x = -o.x;
		nq.y = -o.y;
		nq.z = -o.z;
		nq.w = -o.w;
		cosHalfTheta = -cosHalfTheta;
	}
	if (cosHalfTheta >= 1) {
		return q;
	}
	var r: vec4<f32>;
	var sqrSinHalfTheta = 1 - cosHalfTheta*cosHalfTheta;
	if (sqrSinHalfTheta < 0.001) {
		var s = 1 - t;
		r.w = s*w + t*nq.w;
		r.x = s*x + t*nq.x;
		r.y = s*y + t*nq.y;
		r.z = s*z + t*nq.z;
	return QuatNormalize(r);
	}
	var sinHalfTheta = sqrt(sqrSinHalfTheta);
	var halfTheta = atan2(sinHalfTheta, cosHalfTheta);
	var ratioA = sin((1-t)*halfTheta) / sinHalfTheta;
	var ratioB = sin(t*halfTheta) / sinHalfTheta;
	r.w = w*ratioA + nq.w*ratioB;
	r.x = x*ratioA + nq.x*ratioB;
	r.y = y*ratioA + nq.y*ratioB;
	r.z = z*ratioA + nq.z*ratioB;
return r;
}

//////// import: "slmath-vector2.go"
fn Polar2(angle: f32,radius: f32) -> vec2<f32> {
	return vec2<f32>(radius*cos(angle), radius*sin(angle));
}
fn DivSafe2(v: vec2<f32>, o: vec2<f32>) -> vec2<f32> {
	var nv = v;
	if (o.x != 0) {
		nv.x /= o.x;
	}
	if (o.y != 0) {
		nv.y /= o.y;
	}return nv;
}
fn Negate2(v: vec2<f32>) -> vec2<f32> {
	return vec2<f32>(-v.x, -v.y);
}
fn Length2(v: vec2<f32>) -> f32 {
	return sqrt(v.x*v.x + v.y*v.y);
}
fn LengthSquared2(v: vec2<f32>) -> f32 {
	return v.x*v.x + v.y*v.y;
}
fn Dot2(v: vec2<f32>,o: vec2<f32>) -> f32 {
	return v.x*o.x + v.y*o.y;
}
fn Max2(v: vec2<f32>,o: vec2<f32>) -> vec2<f32> {
	return vec2<f32>(max(v.x, o.x), max(v.y, o.y));
}
fn Min2(v: vec2<f32>,o: vec2<f32>) -> vec2<f32> {
	return vec2<f32>(min(v.x, o.x), min(v.y, o.y));
}
fn Abs2(v: vec2<f32>) -> vec2<f32> {
	return vec2<f32>(abs(v.x), abs(v.y));
}
fn Floor2(v: vec2<f32>) -> vec2<f32> {
	return vec2<f32>(floor(v.x), floor(v.y));
}
fn Ceil2(v: vec2<f32>) -> vec2<f32> {
	return vec2<f32>(ceil(v.x), ceil(v.y));
}
fn Round2(v: vec2<f32>) -> vec2<f32> {
	return vec2<f32>(round(v.x), round(v.y));
}
fn Clamp2(v: vec2<f32>,min: vec2<f32>,max: vec2<f32>) -> vec2<f32> {
	var r = v;
	if (r.x < min.x) {
		r.x = min.x;
	} else if (r.x > max.x) {
		r.x = max.x;
	}
	if (r.y < min.y) {
		r.y = min.y;
	} else if (r.y > max.y) {
		r.y = max.y;
	}return r;
}
fn ClampMagnitude2(v: vec2<f32>, mag: f32) -> vec2<f32> {
	var r = v;
	if (r.x < -mag) {
		r.x = -mag;
	} else if (r.x > mag) {
		r.x = mag;
	}
	if (r.y < -mag) {
		r.y = -mag;
	} else if (r.y > mag) {
		r.y = mag;
	}return r;
}
fn Normal2(v: vec2<f32>) -> vec2<f32> {
	var l = Length2(v);
	if (l == 0) {
		return vec2<f32>(0, 0);
	}return v/(l);
}
fn Cross2(v: vec2<f32>,o: vec2<f32>) -> f32 {
	return v.x*o.y - v.y*o.x;
}
fn DistanceTo2(v: vec2<f32>,o: vec2<f32>) -> f32 {
	return sqrt(DistanceToSquared2(v, o));
}
fn DistanceToSquared2(v: vec2<f32>,o: vec2<f32>) -> f32 {
	var dx = v.x - o.x;
	var dy = v.y - o.y;
return dx*dx + dy*dy;
}
fn CosTo2(v: vec2<f32>,o: vec2<f32>) -> f32 {
	return Dot2(v, o) / (Length2(v) * Length2(o));
}
fn AngleTo2(v: vec2<f32>,o: vec2<f32>) -> f32 {
	var ang = acos(clamp(CosTo2(v, o), f32(-1), f32(1)));
	var cross = Cross2(v, o);
	if (cross > 0) {
		ang = -ang;
	}return ang;
}
fn Lerp2(v: vec2<f32>,o: vec2<f32>, alpha: f32) -> vec2<f32> {
	return vec2<f32>(v.x+(o.x-v.x)*alpha, v.y+(o.y-v.y)*alpha);
}
fn InTriangle2(v: vec2<f32>,p0: vec2<f32>,p1: vec2<f32>,p2: vec2<f32>) -> bool {
	var a = 0.5 * (-p1.y*p2.x + p0.y*(-p1.x+p2.x) + p0.x*(p1.y-p2.y) + p1.x*p2.y);
	var sign = f32(1);
	if (a < 0) {
		sign = f32(-1);
	}
	var s = (p0.y*p2.x - p0.x*p2.y + (p2.y-p0.y)*v.x + (p0.x-p2.x)*v.y) * sign;
	var t = (p0.x*p1.y - p0.y*p1.x + (p0.y-p1.y)*v.x + (p1.x-p0.x)*v.y) * sign;
return s >= 0 && t >= 0 && (s+t) < 2*a*sign;
}
fn Rot90CW2(v: vec2<f32>) -> vec2<f32> {
	return vec2<f32>(v.y, -v.x);
}
fn Rot90CCW2(v: vec2<f32>) -> vec2<f32> {
	return vec2<f32>(-v.y, v.x);
}
fn Rot2(v: vec2<f32>, phi: f32, p0: vec2<f32>) -> vec2<f32> {
	var sinphi = sin(phi);
	var cosphi = cos(phi);
return vec2<f32>(
	p0.x+cosphi*(v.x-p0.x)-sinphi*(v.y-p0.y),
	p0.y+sinphi*(v.x-p0.x)+cosphi*(v.y-p0.y));
}
fn WindowToNDC2(v: vec2<f32>,size: vec2<f32>,off: vec2<f32>, flipY: bool) -> vec3<f32> {
	var n: vec3<f32>;
	var half = size*(0.5);
	n.x = v.x - off.x;
	n.y = v.y - off.y;
	if (flipY) {
		n.y = size.y - n.y;
	}
	n.x = n.x/half.x - 1;
	n.y = n.y/half.y - 1;
return n;
}
fn Dim2(v: vec2<f32>, dim: i32) -> f32 {
	if (dim == 0) {
		return v.x;
	}
	if (dim == 1) {
		return v.y;
	}return f32(0);
}
fn SetDim2(v: vec2<f32>, dim: i32, val: f32) -> vec2<f32> {
	var nv = v;
	if (dim == 0) {
		nv.x = val;
	}
	if (dim == 1) {
		nv.y = val;
	}return nv;
}
fn AddDim2(v: vec2<f32>, dim: i32, val: f32) -> vec2<f32> {
	var nv = v;
	if (dim == 0) {
		nv.x += val;
	}
	if (dim == 1) {
		nv.y += val;
	}return nv;
}
fn SubDim2(v: vec2<f32>, dim: i32, val: f32) -> vec2<f32> {
	var nv = v;
	if (dim == 0) {
		nv.x -= val;
	}
	if (dim == 1) {
		nv.y -= val;
	}return nv;
}
fn MulDim2(v: vec2<f32>, dim: i32, val: f32) -> vec2<f32> {
	var nv = v;
	if (dim == 0) {
		nv.x *= val;
	}
	if (dim == 1) {
		nv.y *= val;
	}return nv;
}
fn DivDim2(v: vec2<f32>, dim: i32, val: f32) -> vec2<f32> {
	var nv = v;
	if (dim == 0) {
		nv.x /= val;
	}
	if (dim == 1) {
		nv.y /= val;
	}return nv;
}

//////// import: "slmath-vector3.go"
fn DivSafe3(v: vec3<f32>, o: vec3<f32>) -> vec3<f32> {
	var nv = v;
	if (o.x != 0) {
		nv.x /= o.x;
	}
	if (o.y != 0) {
		nv.y /= o.y;
	}
	if (o.z != 0) {
		nv.z /= o.z;
	}return nv;
}
fn Negate3(v: vec3<f32>) -> vec3<f32> {
	return vec3<f32>(-v.x, -v.y, -v.z);
}
fn Length3(v: vec3<f32>) -> f32 {
	return sqrt(v.x*v.x + v.y*v.y + v.z*v.z);
}
fn LengthSquared3(v: vec3<f32>) -> f32 {
	return v.x*v.x + v.y*v.y + v.z*v.z;
}
fn Dot3(v: vec3<f32>,o: vec3<f32>) -> f32 {
	return v.x*o.x + v.y*o.y + v.z*o.z;
}
fn Max3(v: vec3<f32>,o: vec3<f32>) -> vec3<f32> {
	return vec3<f32>(max(v.x, o.x), max(v.y, o.y), max(v.z, o.z));
}
fn Min3(v: vec3<f32>,o: vec3<f32>) -> vec3<f32> {
	return vec3<f32>(min(v.x, o.x), min(v.y, o.y), min(v.z, o.z));
}
fn Abs3(v: vec3<f32>) -> vec3<f32> {
	return vec3<f32>(abs(v.x), abs(v.y), abs(v.z));
}
fn Clamp3(v: vec3<f32>,min: vec3<f32>,max: vec3<f32>) -> vec3<f32> {
	var r = v;
	if (r.x < min.x) {
		r.x = min.x;
	} else if (r.x > max.x) {
		r.x = max.x;
	}
	if (r.y < min.y) {
		r.y = min.y;
	} else if (r.y > max.y) {
		r.y = max.y;
	}
	if (r.z < min.z) {
		r.z = min.z;
	} else if (r.z > max.z) {
		r.z = max.z;
	}return r;
}
fn ClampMagnitude3(v: vec3<f32>, mag: f32) -> vec3<f32> {
	var r = v;
	if (r.x < -mag) {
		r.x = -mag;
	} else if (r.x > mag) {
		r.x = mag;
	}
	if (r.y < -mag) {
		r.y = -mag;
	} else if (r.y > mag) {
		r.y = mag;
	}
	if (r.z < -mag) {
		r.z = -mag;
	} else if (r.z > mag) {
		r.z = mag;
	}return r;
}
fn Normal3(v: vec3<f32>) -> vec3<f32> {
	var l = Length3(v);
	if (l == 0) {
		return vec3<f32>(0, 0, 0);
	}return v/(l);
}
fn Cross3(v: vec3<f32>,o: vec3<f32>) -> vec3<f32> {
	return vec3<f32>(v.y*o.z-v.z*o.y, v.z*o.x-v.x*o.z, v.x*o.y-v.y*o.x);
}
fn Floor3(v: vec3<f32>) -> vec3<f32> {
	return vec3<f32>(floor(v.x), floor(v.y), floor(v.z));
}
fn Ceil3(v: vec3<f32>) -> vec3<f32> {
	return vec3<f32>(ceil(v.x), ceil(v.y), ceil(v.z));
}
fn Round3(v: vec3<f32>) -> vec3<f32> {
	return vec3<f32>(round(v.x), round(v.y), round(v.z));
}
fn DistanceTo3(v: vec3<f32>,o: vec3<f32>) -> f32 {
	return sqrt(DistanceToSquared3(v, o));
}
fn DistanceToSquared3(v: vec3<f32>,o: vec3<f32>) -> f32 {
	var dx = v.x - o.x;
	var dy = v.y - o.y;
	var dz = v.z - o.z;
return dx*dx + dy*dy + dz*dz;
}
fn Lerp3(v: vec3<f32>,o: vec3<f32>, alpha: f32) -> vec3<f32> {
	return vec3<f32>(v.x+(o.x-v.x)*alpha, v.y+(o.y-v.y)*alpha, v.z+(o.z-v.z)*alpha);
}
fn CosTo3(v: vec3<f32>,o: vec3<f32>) -> f32 {
	return Dot3(v, o) / (Length3(v) * Length3(o));
}
fn AngleTo3(v: vec3<f32>,o: vec3<f32>) -> f32 {
	var ang = acos(clamp(CosTo3(v, o), f32(-1), f32(1)));
	var cross = Cross3(v, o);
	var ax = abs(cross.x);
	var ay = abs(cross.y);
	var az = abs(cross.z);
	if (az >= ay && az >= ax) {
		if (cross.z > 0) {
			ang = -ang;
		}
	} else if (ay >= az && ay >= ax) {
		if (cross.y > 0) {
			ang = -ang;
		}
	} else if (ax >= az && ax >= ay) {
		if (cross.x > 0) {
			ang = -ang;
		}
	}return ang;
}
fn ProjectOnVector3(v: vec3<f32>,o: vec3<f32>) -> vec3<f32> {
	var on = Normal3(o);
return on*(Dot3(v, on));
}
fn ProjectOnPlane3(v: vec3<f32>,planeNormal: vec3<f32>) -> vec3<f32> {
	return v-(ProjectOnVector3(v, planeNormal));
}
fn Reflect3(v: vec3<f32>,normal: vec3<f32>) -> vec3<f32> {
	return v-(normal*(2 * Dot3(v, normal)));
}
fn NDCToWindow3(v: vec3<f32>, size: vec2<f32>,off: vec2<f32>, near: f32,far: f32, flipY: bool) -> vec3<f32> {
	var w: vec3<f32>;
	var half = size*(0.5);
	w.x = half.x*v.x + half.x;
	w.y = half.y*v.y + half.y;
	w.z = 0.5*(far-near)*v.z + 0.5*(far+near);
	if (flipY) {
		w.y = size.y - w.y;
	}
	w.x += off.x;
	w.y += off.y;
return w;
}
fn Vec3FromVec4(v: vec4<f32>) -> vec3<f32> {
	return vec3<f32>(v.x, v.y, v.z);
}
fn Dim3(v: vec3<f32>, dim: i32) -> f32 {
	if (dim == 0) {
		return v.x;
	}
	if (dim == 1) {
		return v.y;
	}return v.z;
}
fn SetDim3(v: vec3<f32>, dim: i32, val: f32) -> vec3<f32> {
	var nv = v;
	if (dim == 0) {
		nv.x = val;
	}
	if (dim == 1) {
		nv.y = val;
	}
	if (dim == 2) {
		nv.z = val;
	}return nv;
}

//////// import: "slmath-vector4.go"
fn Vec4FromVec3(v: vec3<f32>, w: f32) -> vec4<f32> {
	return vec4<f32>(v.x, v.y, v.z, w);
}
fn DivSafe4(v: vec4<f32>, o: vec4<f32>) -> vec4<f32> {
	var nv = v;
	if (o.x != 0) {
		nv.x /= o.x;
	}
	if (o.y != 0) {
		nv.y /= o.y;
	}
	if (o.z != 0) {
		nv.z /= o.z;
	}
	if (o.w != 0) {
		nv.w /= o.w;
	}return nv;
}
fn Negate4(v: vec4<f32>) -> vec4<f32> {
	return vec4<f32>(-v.x, -v.y, -v.z, -v.w);
}
fn Length4(v: vec4<f32>) -> f32 {
	return sqrt(v.x*v.x + v.y*v.y + v.z*v.z + v.w*v.w);
}
fn LengthSquared4(v: vec4<f32>) -> f32 {
	return v.x*v.x + v.y*v.y + v.z*v.z + v.w*v.w;
}
fn Dot4(v: vec4<f32>,o: vec4<f32>) -> f32 {
	return v.x*o.x + v.y*o.y + v.z*o.z + v.w*o.w;
}
fn Max4(v: vec4<f32>,o: vec4<f32>) -> vec4<f32> {
	return vec4<f32>(max(v.x, o.x), max(v.y, o.y), max(v.z, o.z), max(v.w, o.w));
}
fn Min4(v: vec4<f32>,o: vec4<f32>) -> vec4<f32> {
	return vec4<f32>(min(v.x, o.x), min(v.y, o.y), min(v.z, o.z), min(v.w, o.w));
}
fn Abs4(v: vec4<f32>) -> vec4<f32> {
	return vec4<f32>(abs(v.x), abs(v.y), abs(v.z), abs(v.w));
}
fn Floor4(v: vec4<f32>) -> vec4<f32> {
	return vec4<f32>(floor(v.x), floor(v.y), floor(v.z), floor(v.w));
}
fn Ceil4(v: vec4<f32>) -> vec4<f32> {
	return vec4<f32>(ceil(v.x), ceil(v.y), ceil(v.z), ceil(v.w));
}
fn Round4(v: vec4<f32>) -> vec4<f32> {
	return vec4<f32>(round(v.x), round(v.y), round(v.z), round(v.w));
}
fn Clamp4(v: vec4<f32>,min: vec4<f32>,max: vec4<f32>) -> vec4<f32> {
	var r = v;
	if (r.x < min.x) {
		r.x = min.x;
	} else if (r.x > max.x) {
		r.x = max.x;
	}
	if (r.y < min.y) {
		r.y = min.y;
	} else if (r.y > max.y) {
		r.y = max.y;
	}
	if (r.z < min.z) {
		r.z = min.z;
	} else if (r.z > max.z) {
		r.z = max.z;
	}
	if (r.w < min.w) {
		r.w = min.w;
	} else if (r.w > max.w) {
		r.w = max.w;
	}return r;
}
fn ClampMagnitude4(v: vec4<f32>, mag: f32) -> vec4<f32> {
	var r = v;
	if (r.x < -mag) {
		r.x = -mag;
	} else if (r.x > mag) {
		r.x = mag;
	}
	if (r.y < -mag) {
		r.y = -mag;
	} else if (r.y > mag) {
		r.y = mag;
	}
	if (r.z < -mag) {
		r.z = -mag;
	} else if (r.z > mag) {
		r.z = mag;
	}
	if (r.w < -mag) {
		r.w = -mag;
	} else if (r.w > mag) {
		r.w = mag;
	}return r;
}
fn Normal4(v: vec4<f32>) -> vec4<f32> {
	var l = Length4(v);
	if (l == 0) {
		return vec4<f32>(0, 0, 0, 0);
	}return v/(l);
}
fn Lerp4(v: vec4<f32>,o: vec4<f32>, alpha: f32) -> vec4<f32> {
	return vec4<f32>(v.x+(o.x-v.x)*alpha, v.y+(o.y-v.y)*alpha,
		v.z+(o.z-v.z)*alpha, v.w+(o.w-v.w)*alpha);
}
fn PerspDiv4(v: vec4<f32>) -> vec3<f32> {
	return vec3<f32>(v.x/v.w, v.y/v.w, v.z/v.w);
}
fn Dim4(v: vec4<f32>, dim: i32) -> f32 {
	if (dim == 0) {
		return v.x;
	}
	if (dim == 1) {
		return v.y;
	}
	if (dim == 2) {
		return v.z;
	}return v.w;
}
fn SetDim4(v: vec4<f32>, dim: i32, val: f32) -> vec4<f32> {
	var nv = v;
	if (dim == 0) {
		nv.x = val;
	}
	if (dim == 1) {
		nv.y = val;
	}
	if (dim == 2) {
		nv.z = val;
	}
	if (dim == 3) {
		nv.w = val;
	}return nv;
}