// Code generated by 'yaegi extract cogentcore.org/lab/plotcore'. DO NOT EDIT.

package gui

import (
	"cogentcore.org/lab/plotcore"
	"reflect"
)

func init() {
	Symbols["cogentcore.org/lab/plotcore/plotcore"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewPlot":           reflect.ValueOf(plotcore.NewPlot),
		"NewPlotEditor":     reflect.ValueOf(plotcore.NewPlotEditor),
		"NewPlotterChooser": reflect.ValueOf(plotcore.NewPlotterChooser),
		"NewSubPlot":        reflect.ValueOf(plotcore.NewSubPlot),

		// type definitions
		"Plot":           reflect.ValueOf((*plotcore.Plot)(nil)),
		"PlotEditor":     reflect.ValueOf((*plotcore.PlotEditor)(nil)),
		"PlotterChooser": reflect.ValueOf((*plotcore.PlotterChooser)(nil)),
	}
}
