// Code generated by 'yaegi extract cogentcore.org/lab/stats/glm'. DO NOT EDIT.

package nogui

import (
	"cogentcore.org/lab/stats/glm"
	"reflect"
)

func init() {
	Symbols["cogentcore.org/lab/stats/glm/glm"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewGLM": reflect.ValueOf(glm.NewGLM),

		// type definitions
		"GLM": reflect.ValueOf((*glm.GLM)(nil)),
	}
}
